### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by davidxd33** [echoroleplay/feedback#1]
## Bug Details

**Description:** Please describe the bug in as much detail as possible. Explain what you expected to happen and what actually happened. If you encountered an error message, please include it here.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Step one
2. Step two
3. ...

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.

**Actual Behavior:** Describe what actually happened instead.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 

_Thank you for your contribution to our server. Your report is greatly appreciated and will help us to enhance the overall gaming experience._

**Comment by FlawwsX** [comment]
You don’t deserve help.
