### ISSUE TITLE
Alarm goes off despite disabling security.

### ISSUE THREAD

**Issue by SurgeGit** [echoroleplay/feedback#100]
**Description:** The alarm went off when I was robbing a house after disabling the security and even crouching.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get a mirror park house on linkup.
2. Disable the security.
3. Rob the house (while crouched)
4. Set off the alarm anyway.

**Expected Behavior:** Alarm does not go off as it has been disabled.

**Actual Behavior:** Alarm goes off, causing the police to come and having to flee for your life and nearly dying (lol)

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1cAjQguNhvsEwQ/2lVsukHw9tUp?invite=cr-MSxrMXEsMTg0Nzc4ODEzLA

**Comment by Alexmonlol** [comment]
Yeah, So I had the same thing now twice. 

Went back into the first house multiple time and I could disable it everytime, it went off.
-Alarm goes off after 2 exact minutes.

If you do the puzzle correct, and try to disable it again right after. You'll get a popup on the top right of your screen with the text "Alarm is already disabled."

At first I thought I had to do more things, so for the 2nd house I got I went with tons of stuff. But the realised that it might be bugged.

**Comment by funkffn** [comment]
I've encountered this issue with every house beyond the ones in South side. Mirror Park, Vespucci/Rockford/lower Vinewood, and upper Vinewood houses.

Each time you disable the alarm, you can still third eye the device, and after you cross a certain threshold in the house the alarm goes off, 10 times outta 10.

**Comment by SurgeGit** [comment]
Hmm. I did one of the big houses and disabled the alarm just fine and it did not go off. Only had problems in mirror park and other houses with that interior. Strange

**Comment by damightylamb** [comment]
There is still a possibility of it going off for a reason. Just because the alarm is "disabled" does not mean you're 100% clear

**Comment by SurgeGit** [comment]
Can you confirm then in the clip I provided that the alarm was supposed to go off?

**Comment by damightylamb** [comment]
Hard to tell, but from what I see, yes.

**Comment by funkffn** [comment]
@damightylamb i had considered that and have been looking to see if thats the case.


There is some other minor issues with the disabling security. The polyzone (or whatever lets you third eye things) on the mirror park houses is very small for the device, you oftentimes have to find the exact pixel.

The animation for performing the higher tier hacks, sometimes you get stuck inside them for prolonged periods even after the hacks complete. Spamming the menu/GPS buttons seems to shake you loose of it. 

If its intended all good, but just bringing it up.

Will find footage of the animation issue next time i'm in.

**Comment by SurgeGit** [comment]
> Hard to tell, but from what I see, yes.

Wow really? Damn ok.

**Comment by damightylamb** [comment]
> Spamming the menu/GPS buttons seems to shake you loose of it.

Just wait for the animation to end. You dont have to spam anything.

**Comment by SurgeGit** [comment]
I like how in the house where the alarm didn't go off after disabling security I attacked the local and walked around loudly and nothing happened but when I crouched it went off again lol. Will have to try and find out what causes it then I guess. Feel free to close

**Comment by Alexmonlol** [comment]
> Hard to tell, but from what I see, yes.

So, I've gotten 2 of these Mirror Park houses now. And I've stayed around after PD left just to try to disable the alarm again. 

Succesfully done it multiple times. And everytime, straight after 2 minutes of entering the house. Even if i stand still crouched next to the disabled alarm. It will still go off after 2 minutes.

**Comment by ATypicalXY** [comment]
Happened to me too today. Sometimes it works, sometimes it goes off after disabling. Happened in Chumash and homes off Rockford.

**Comment by Arcfull** [comment]
> There is still a possibility of it going off for a reason. Just because the alarm is "disabled" does not mean you're 100% clear

Not sure how that makes any sense at all. Why even label it as "Disable Security System" if completing the hack doesn't stop it from going off? If it's supposed to act as a delay, then that should be articulated. It's not like you could even go back and do it again after you finish it, so once it goes off for no reason you're fucked. I would understand that doing something like shooting, jumping around, making noise, alerting the local, etc. would make it go off, but 9 times out of 10 it just goes off regardless. The only reason it's not 10 out of 10 times is because the locals will alert to you for no reason as well.

I feel like if you deal with the alarm, and there either isn't a local or you kill them with a suppressed weapon, you shouldn't have any more risk of alerting the cops, because if that's not the case then everyone is just gonna sprint around in the houses and speedrun them instead of pretending there's some chance that they won't alert anyone.

**Comment by SurgeGit** [comment]
Like I said previously I do think the alarms are really harsh. I haven't been able to not set off the alarm all but once. Although judging from whats being said theres probably something big we are all missing about it so lets see

**Comment by ATypicalXY** [comment]
> 

not sure what we are "missing". disabling an alarm should do just that. we already have to contend with the disabling game. the mechanic is strange and not worth it for me, at this time. $.02

**Comment by FlawwsX** [comment]
The alarm is temporary, just the notification informing you of this was not working.

It has been resolved now though!
