### ISSUE TITLE
Motel Kicked me out 

### ISSUE THREAD

**Issue by Creah** [echoroleplay/feedback#103]
I was Renting a Room had just payed to have my room Stay exstended and when i logged in the next day my room was Gone. there isn't even a front desk to give me my things. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. I woke up.
2. hotel is gone.

**Expected Behavior:** Not sure If the whole hotel is gone there isn't much anyone can do to recreate it. I Expected to wake up in my Room or atleast be able to get my things back from the Check out lady.

**Actual Behavior:** I didn't wake up in my room?

**Screenshot(s)/Video(s):**
Proof of payment
![image](https://github.com/echoroleplay/feedback/assets/135556913/13a6cbc4-acb5-4c7d-a632-511930a84854)

Location of hotel. the one just above my Curser.
![image](https://github.com/echoroleplay/feedback/assets/135556913/0a362d13-6677-486f-a7e7-2292b944aaa4)

**Comment by SurgeGit** [comment]
This is intentional they said it got removed as it shouldn't have been in the game. I think Flawws said you can open a compensation ticket if you want, thats what I have done anyway 👍

**Comment by davidxd33** [comment]
This is not a bug, make a compensation ticket as some motels were removed.
