### ISSUE TITLE
Queueing for jobs doesn't work (Drug Runs)

### ISSUE THREAD

**Issue by KomitDzn** [echoroleplay/feedback#104]
**Description:** Please **replace me** with a description of the bug in as much detail as possible.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get 1600 crypto
2. get 5 members
3. queue for a drug run

**Expected Behavior:** give me the job

**Actual Behavior:** says I lack reputation

**Screenshot(s)/Video(s):** https://cdn.discordapp.com/attachments/1094713307111374848/1115047297768763392/image.png
![image](https://github.com/echoroleplay/feedback/assets/135557733/4bc5c4d6-d4f5-4860-87e8-928ac7f463af)

**Comment by damightylamb** [comment]
Not a bug :)
