### ISSUE TITLE
ATM Hacking device - Linking up with another phone/ person.

### ISSUE THREAD

**Issue by Alexmonlol** [echoroleplay/feedback#105]
**Description:** ATM Hacking device - Linking up with another phone/ person.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Person A (who linked up with the device first) puts it in the ATM.
2. Starts hacking.
3. Person B Pulls out the device and it will be linked up to ~~Person A's~~ Person B phone 

**Expected Behavior:** Stay linked to Person A.

**Actual Behavior:** Gets linked to Person B.

**Screenshot(s)/Video(s):** Not sure if this will help.

Edit: change to Reporoduction Steps. 3. From person A to person B

**Comment by FlawwsX** [comment]
How is this an issue? If it's linked to someone's phone, it shouldn't unlink just because it entered the hands of someone else.

**Comment by damightylamb** [comment]
Pushing fix for tomorrow.
