### ISSUE TITLE
Peds falling through ground for pawn runs

### ISSUE THREAD

**Issue by DonJaker** [echoroleplay/feedback#11]
**Description:** When delivering little pawn packages the local falls through the map preventing you from delivering/completing your deliveries. 

**Reproduction Steps:**  
1. Package goods and start a small pawn run
2. Deliver packges 
3. Either complete the deliveries successfully or see a local drop down and dissapear with the marker still on the minimap.

**Expected Behavior:** For the local to remain in place when delivering a package.

**Actual Behavior:** The local sometimes drops through the ground.

**Screenshot(s)/Video(s):** None available, if happens again I will provide a video.

**Comment by davidxd33** [comment]
I am unable to reproduce this issue. I was able to do the small pawn runs and the peds were fine for me. Please reopen if this happens again with a video.
