### ISSUE TITLE
Boosting Queue

### ISSUE THREAD

**Issue by Juhux** [echoroleplay/feedback#110]
Description: Boost queue doesn't move after one completed boost and sometimes without even completing one. I have seen previous bug reports about it in which it was stated that it is working normal after a fix was pushed. However, getting none or one boost during a whole restart and even over the course of several restarts seems far from intended 

Reproduction Steps:
1. Queue in for a boost right after a restart
2. Get a boost thirty minutes after restart
3. Complete boost and queue again
4. Sit in queue and not get a boost for the entirety of the restart

Expected Behavior: Get regular boosts throughout an entire restart with cooldowns in between (which happened once in one restart yesterday which seemed normal, meaning that something is going wrong in other restarts)

Actual Behavior: Get one boost per restart and sometimes none and hence keep waiting in queue for hours on end in different restarts and completing barely any boosts over the course of days.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by FlawwsX** [comment]
Resolved
