### ISSUE TITLE
ATM Payout

### ISSUE THREAD

**Issue by MrE1ectric** [echoroleplay/feedback#113]
**Description:** When hitting an ATM it is paying 0-7 notes. I am not sure if a few Zeros were missed or the wrong currency was used but when a device costs between $2,500-$5,000 depending on the group or contacts you know the payout is not worth buying or trying. Now the hack itself is excellent and I love how it works but the payout seems to be the only issue as of now

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Rob an ATM
2. Collect Money
3. Be confused that an ATM has little to no money in it due to the device costing way more than this is worth

**Expected Behavior:** A better payout or maybe marked bills as an ATM will usually hold an average of $10,000 of fresh bills

**Actual Behavior:** Criminals get scammed by ATm payout

**Comment by funkffn** [comment]
Plus 1, the hack is really cool to puzzle out and its very immersive. I pretty much like everything about it except its payout.

**Comment by Freakerdoodle** [comment]
+1, every one i've hacked has been empty

**Comment by FlawwsX** [comment]
Increased slightly

**Comment by FlawwsX** [comment]
Also, not a bug.
