### ISSUE TITLE
House Robbery Locals alerting for no reason.

### ISSUE THREAD

**Issue by Arcfull** [echoroleplay/feedback#114]
**Description:** Half the time (in my experience) entering a House and looting, the local inside will alert for no reason, presumably alerting the police as well.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Enter House Robbery
2. Disable Security
3. Loot a bit
4. The local gets alerted for seemingly no reason.

**Expected Behavior:** The local only alerts to the security system, or to quick movement, loud noises, etc.

**Actual Behavior:** The local alerts regardless.

**Comment by Ponnkun** [comment]
Duplicate of Issue #100
