### ISSUE TITLE
Parked Cars in penthouse not able to be seen or taken out

### ISSUE THREAD

**Issue by JaxTeller10** [echoroleplay/feedback#115]
**My cars that I parked in my penthouse are stuck in there and i cant see them.:** Please ** Help me remove my cars from there so I can drive them again until this is fixed.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Step one - Make cars be visible in the penthouse garage.
2. Step two - Make cars be able to pull out of Penthouse garage.
3. ...

**Expected Behavior:** Be able to Pull out and also see the cars parked in penthouse garage.

**Actual Behavior:** Not being able to access or see my cars. 

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by davidxd33** [comment]
Please upload of vehicle of this happening as well as a screenshot of your vehicles in the phone showing where they are parked.
