### ISSUE TITLE
City Works job used to display "result" after inspecting part

### ISSUE THREAD

**Issue by Vallenesca** [echoroleplay/feedback#117]
**Description:** City works job (side job) used to display the "result" after inspecting the part, to let us know if it needed to be fixed or not. It used to be a pop up on the left side like how it comes up "Press E to inspect part" that said either 10% or 80%. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Inspect the part once at the spot
2. Get the result
3. No result comes up, and your left wondering for a moment if it needs fixing or not before the "press E to replace part" pops up on the screen like 5 seconds later

**Expected Behavior:** Get a Result of ether 10% or 80% and not be stuck wondering if you can leave, or if it does need repairing (specially if you get distracted by a cat/children and dont see it)

**Actual Behavior:** nothing happens for a few seconds after "getting result" before you likely get a "fix part" popping up on the left.

**Comment by StuxxyOfficial** [comment]
Issue should now be resolved and the fix is live.
