### ISSUE TITLE
The Pro Laser 4 Radar gun time is not in EST and is out of sink with AXON

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#12]
Issue Description: The Pro Laser 4 Radar gun time is not in EST and is out of sink with AXON

Steps to reproduce the issue:
1. Pull out Pro Laser 4 radar gun
2. Clock a few people speeding
3. use the left and right arrow keys to browse the radar lock history

What's the expected result? The time listed should be in EST
What's the actual result? Time listed isn't in EST

Additional details / screenshot(s): take note of the times in red

![05_30_2023 - SS2549](https://github.com/echoroleplay/feedback/assets/134963542/c75dcaaa-6e85-4207-a12a-e8f0429ff959)

**Comment by Ponnkun** [comment]
Appears that the Lidar Gun is in UTC
