### ISSUE TITLE
Adjust the alarm to be a little less harsh after "disabling."

### ISSUE THREAD

**Issue by SurgeGit** [echoroleplay/feedback#125]
**Suggestion Description**
The alarm will trigger regardless of it being "disabled" and from my testing it is virtually impossible to distinguish what you are doing wrong to trigger it. This leaves no way for your character to prevent it being set off in the future. From what I can tell there are no clues or no real way to figure out why the alarm goes off after you've just supposedly disabled it with a difficult hack, 99% of the time it feels like you never turned the alarm off at all. 

I am suggesting either the alarm trigger becomes less harsh/less common allowing people who have "disabled" the alarm to loot for a bit longer or with a bit more freedom than the current. OR, there are hints or other ways that the player can understand why the alarm is going off and what they can do to prevent it.

**Reason**
The hacks are difficult and you must go out of your way to get a hacking device. I believe you should be able to disable the security system in a more effective way and have more freedom when robbing because of this. Else, it makes the hack feel unrewarding and somewhat pointless compared to the concentration it requires.

**Additional context**
I have been doing house robberies since the Spring update came. I can only recall one time where I have robbed a house without the alarm going off at all and I robbed it in no different way to all of the others. Every other house the alarm has been triggered despite any and all efforts to prevent/discover why the alarm went off involving crouching, removing my shoes, walking in increments. Without fail the alarm goes off after 1-5 cabinets no matter how hard I try and I feel there should be more leniency.

I am happy to hear what others think and also interested to see what the Dev perspective of this is and how often they intended disabled alarms to go off.

**Comment by SurgeGit** [comment]
Just to add on to this - It also appears that the security system gets re-enabled. In my most recent test, I disabled the security system with the hack. I checked to see if I could hack again and I could not. Then 10 seconds later the alarm got set off despite my crouching and barely moving across one room. Then I went back to the panel and it let me attempt to hack again. I am not sure what this whole alarm thing is about but it seems really harsh especially with the hacks you have to do.

**Comment by FlawwsX** [comment]
It's fine as is.
