### ISSUE TITLE
Invisibility from boxes

### ISSUE THREAD

**Issue by parkerstan93** [echoroleplay/feedback#13]
**Description:** new boxes near warehouse make you invisible

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. jump on box
2. be invisible 
3. jump down
4. still invisible

**Expected Behavior:** not be invisible, or at least go back to normal when jumping off

**Actual Behavior:** invisibility forever

**Screenshot(s)/Video(s):** https://clipchamp.com/watch/zw0ADRQE6MG

**Comment by FlawwsX** [comment]
According to the mapping folk:
> It’s just props disappearing and not syncing properly. He probably jumped on the box while it flickered causing him to also be invisible. Same happens with dumpsters that get hit and start buggin. Not sure if we can do anything about it
