### ISSUE TITLE
Alarm keeps going off after disabling security

### ISSUE THREAD

**Issue by feedmeee-x** [echoroleplay/feedback#131]
**Description:** Robbed a house in paleto. Failed the hack the first time. Alarm went off. Succeeded the hack after that and it kept going off. Did it once more, and alarm still triggered again. I am unsure if this is intentional but if it is, it wouldn't make sense to allow me to succeed it after if it has no effect.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Fail paleto house hack once
2. Do the hack again and succeed

**Expected Behavior:** The security system goes down when the hack succeeds

**Actual Behavior:** Subsequent hacks have no effect

**Comment by Ponnkun** [comment]
Duplicate of #100
