### ISSUE TITLE
House Robberies causes shots fired calls and trackers to be appear in random locations and not the house itself

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#133]
**Description:** House Robberies causes dispatch calls to appear in random locations and not the house itself

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. go into a house that's being robbed
2. shoot a gun

**Expected Behavior:** The shots fired call will be at where the house is that was being robbed

**Actual Behavior:** The shots fired call will be in a weird location

Seems to just be an oversight with instancing the houses in the way they currently are.

Below is the location of the house being robbed on the map, clearly in vinewood hills:
![06_07_2023 - SS2718](https://github.com/echoroleplay/feedback/assets/134963542/1aa87e72-cfea-4954-8257-93e92e120497)

Next we have the dispatch call saying that the same house being robbed is on palomino freeway:
![06_07_2023 - SS2721](https://github.com/echoroleplay/feedback/assets/134963542/14f197c4-c1c4-452e-8f8d-ae2a0285a98a)

When the officers breach the house their blips show them to be in the middle of know where due to the instancing
![06_07_2023 - SS2719](https://github.com/echoroleplay/feedback/assets/134963542/a22142c1-2427-4972-948a-b5bb7bab4b5b)

When they shoot inside the house it also has the shots fired call get dispatched to that location
![06_07_2023 - SS2720](https://github.com/echoroleplay/feedback/assets/134963542/d92f16aa-d184-44eb-a257-6da4aae93371)

**The major issue with this is that people could possibly take advantage of this and just willy nilly shoot the home owners and shoot around inside the house and we wouldn't know which one it is unless the alarm goes off. That and the dispatch call outs for the wrong locations are a little annoying.**

**Comment by stayingquietnow** [comment]
I previously had seen the dispatch for house robberies frequently show the correct locations, but today the notifications all show up as the location where they are instanced at.
![2023-06-09_20 26 45](https://github.com/echoroleplay/feedback/assets/136142363/8cbf4f25-fdaf-4cba-9fa9-c44248395246)
![2023-06-09_20 26 59](https://github.com/echoroleplay/feedback/assets/136142363/9b9781e2-f995-4077-8c52-4955dd0514ab)

**Comment by FlawwsX** [comment]
I think @damightylamb fixed this.
