### ISSUE TITLE
Boosting completes when switching seats

### ISSUE THREAD

**Issue by Sorrowvi** [echoroleplay/feedback#140]
**Description:** Switched seats to try different things to remove the tracker and car poofed away and completed itself? Did it twice.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Lockpick the car
2. Start driving the car
3. Switched seats to try different devices to remove tracker
4. Car disappears and completes the boost

**Expected Behavior:** Car shouldn't disappear
**Actual Behavior:** It poofed and completed the boost

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1d7CGXdCiNOFKo/d1337XS5yM4L?invite=cr-MSxFMEIsMTIzMDk5ODA5LA

**Comment by QuiggUK** [comment]
Same thing happened to us, instead it was right at the start of the boost, the person that claimed it wasn't in driver and got the notification as we pulled away from the pickup and the car went poof but the payout was given.

**Comment by FlawwsX** [comment]
This has been resolved
