### ISSUE TITLE
skateboard emotes dont stick while moving

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#142]
**Description:** skateboard emotes don't stick while moving, If you sit on the board and move you revert to standing up

**Reproduction Steps:** 
1. Get on the skateboard
2. Use F1 wheel menu and chose an emote
3. move foward on the board

**Expected Behavior:** the skateboard moves and you continue to do what ever emote you chose from the F1 wheel menu

**Actual Behavior:** when you start moving the emote resets to the standing up one

**Screenshot(s)/Video(s):** 
https://medal.tv/games/gta-v/clips/1dbuCVj6DQiPaJ/d1337A6vdQsQ?invite=cr-MSxQY0YsMTc5NzI4NDkzLA

**Comment by C4LLZ** [comment]
@FlawwsX This was removed last second before we implemented it. Should the emote stop when moving?

**Comment by RADSTAR55** [comment]
If it was removed it would be really awesome if it could be a thing as I could use it as alternative to wheelchairs. That and currently no one emotes on the boards from what I have seen

**Comment by FlawwsX** [comment]
This is intentional. You should not be able to sit and ride
