### ISSUE TITLE
Make Dr.Lamb's Equipment linkup jobs much harder and/or less frequent

### ISSUE THREAD

**Issue by Ooodee** [echoroleplay/feedback#153]
Suggestion Description
The Aircraft Carrier is good, it is actually challenging and is high risk. However, the other three locations (so far) don't have any resistance or risk, you just pull up and loot a crate and boom you and whoever is with you now have 10s of thermite and cards. Add waves of locals to all jobs and/or limit the equipment jobs that are happening. 

Reason
City went from not one Vangelico being hit to constant back to back Vangelicos. Groups of friends/Gangs now literally have tens of thermite and the grind situation is back to square one. There should be some kind of balance, nobody liked not hitting a job for 2 weeks but nobody likes jobs being hit 24/7 either. The situation right now is worse than the crafting situation, loot crates and hit jobs with little to no effort whatsoever. Make the jobs actual jobs that need planning to pull off and get the equipment needed and limit them. Nobody should be able to get tens of thermite in 2 storms.

**Comment by damightylamb** [comment]
Only reason it was set up the way it is was because I had to take an emergency trip and wouldn't be back till Sunday. When I get back adjustments will be made
