### ISSUE TITLE
Not able to customise M16 at customisation table @VPD

### ISSUE THREAD

**Issue by xS0uth** [echoroleplay/feedback#154]
**Description:** When I attempt to customise my M16, the camera and everything is up but I can not do anything to do weapon nor press ESC to cancel.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Have a M16 in your hand.
2. Go to the customisation table and try to customise your M16.

**Expected Behavior:** You should be able to change your weapons colour and do other customisations.

**Actual Behavior:** You can't do anything to your gun.

**Screenshot(s)/Video(s):** 
![Uploading Zrzut ekranu 2023-06-10 100257.png…]()

**Comment by RanThoseAarons** [comment]
Hello,

All gun customization seems to be causing issues and there is already a bug report in place so this one will be closed.
