### ISSUE TITLE
Boosting not giving Hacker Rep

### ISSUE THREAD

**Issue by Breakfastpls** [echoroleplay/feedback#155]
The hacker does not receive rep when turning in the boost

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Invite Hacker
2. Complete Hack
3. Turn in vehicle to NPC
4.  Person who claimed gets rep the hacker does not. 

**Expected Behavior:** Hacker and the Driver both get Rep

**Actual Behavior:** Person who claims (driver). Is the only person who receives rep

**Comment by Alexmonlol** [comment]
+1

**Comment by FlawwsX** [comment]
Resolved
