### ISSUE TITLE
No longer able to buy attachments as a criminal

### ISSUE THREAD

**Issue by feedmeee-x** [echoroleplay/feedback#157]
**Description:** No longer able to buy attachments as a criminal

**Reproduction Steps:**
1. Go to the spot where you can modify your gun
2. Try to modify it

**Expected Behavior:** Able to modify gun

**Actual Behavior:** Just able to view the weapon and accept

**Screenshot(s)/Video(s):**

**Comment by RanThoseAarons** [comment]
Hello,

All gun customization seems to be causing issues and there is already a bug report in place so this one will be closed.
