### ISSUE TITLE
 Floating weed plants that have collisions because of people setting their housing interior high in the sky via the Z-Axis

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#16]
Issue Description: Floating weed plants that have collisions because of people setting their housing interior high in the sky via the Z-Axis. I have crashed into floating weed and blown up a few times in chases and I have seen others do it as well. It's super annoying honestly.

Steps to reproduce the issue:
1. Set the Z-Axis of your house interior so that its above ground
2. plant weed inside the house
3. Go outside and fly a heli at roughly where the Z-Axis is

What's the expected result? shouldn't be able to see the plants and if you fly into them you shouldn't blow up
What's the actual result? They pop up last second so there is no reaction time to dodge them and you blow up

Screenshot:
![04_13_2023_-_SS1766](https://github.com/echoroleplay/feedback/assets/134963542/689bf753-2950-44a8-a764-a08e0df24279)

**Comment by FlawwsX** [comment]
This is being looked into.

**Comment by FlawwsX** [comment]
Fixed for restart
