### ISSUE TITLE
Having a mask on in your ID photo

### ISSUE THREAD

**Issue by CadillacKoopa** [echoroleplay/feedback#160]
**Suggestion Description**
I think this should be considered low quality RP

**Reason**
It is difficult enough to be able to tell if someone is using a stolen ID. Plus no DMV or DPS would allow a masked photo. Identity should be taken a bit more seriously in my opinion. 

**Additional context**
none

**Comment by Acheron420** [comment]
I think this should be dealt with IC'ly, let PD with charge those who's got a mask in their photo ID.
I say this as someone who's got their ID stolen, and might get charged for it under that ID.

**Comment by C4LLZ** [comment]
100% an IC issue

**Comment by FlawwsX** [comment]
It’s not an IC issue. There’s already rules in place and an announcement made in the past that deemed this an OOC rule break.
