### ISSUE TITLE
Move Dr Lamb notifications for shipment to the LinkIn app instead.

### ISSUE THREAD

**Issue by karichandesu** [echoroleplay/feedback#163]
**Suggestion Description**
Move Dr Lamb notifications for shipment to the LinkIn app to be a randomized offer people have to check for in the app.

**Reason**
QOL- The notifications are so frequent, you get one like every 30 minutes. It can be quite annoying to have to decline them all the time. Maybe changing it so that it's a brief 2-3 second ping notification, something like 'You have a message from... ' sortof similiar to the tsunami notifications, which then let them know to check the Linkin app for their offer that last 30 seconds to a minute before it disappears. 

**Additional context**
Dr Lamb, I feel like, is meant to be a bit more stealthy and secretive. People who do not have the LinkIn app do not receive his messages so I feel like it adds a bit of secrecy to the missions he wants to be completed.

**Comment by damightylamb** [comment]
Only reason it's how it is right now was because I was gone from Thursday until later today and wanted people to get materials for crime. It will be changing once I get home
