### ISSUE TITLE
Cars vanish during house robberies

### ISSUE THREAD

**Issue by TroyTates** [echoroleplay/feedback#164]
**Description:**during house robberies after entering the house and leaving, the car will be gone leaving you stranded same when using a personal car, you can track it and itll appear infront of you quite immersion breaking
**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. enter house robbery, or house/warehouse
2. leave house , ive had it happen just entering and leaving so no specific timeframe
3. car gone my fat ass gotta run

**Expected Behavior:** i expect the car i parked outside to still be outside or hidden where i put it
**Actual Behavior:** the car is gone completely unless its a personal car you can track it and itll appear

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by Creeamy** [comment]
This happened to me aswell
