### ISSUE TITLE
Fleeca bank scuff

### ISSUE THREAD

**Issue by ImUnreliable** [echoroleplay/feedback#166]
Claimed the job but doesn't give a bank, or give a location to get a key

1. Queue for a bank
2. Get the notification to spend 800 EVC to claim a bank
3. No notification comes through to hit any bank or any type of hint on what to do.

To give a location to rob "San Vitas" etc.

Nothing happened just took my 800 EVC

**Comment by damightylamb** [comment]
Can't seem to replicate. If it happens again, please open another ticket.
