### ISSUE TITLE
Alarm goes off ~3minutes after disabling.

### ISSUE THREAD

**Issue by Acheron420** [echoroleplay/feedback#167]
**Description:** As the title says, the alarm goes off after 3 minutes; making this report because I don't think it's intentional. It makes zero sense to have a hacking device that only disables the alarm for 3 minutes.
I think the cause is when I took my knife out, which might've triggered the alarm. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. enter the house
2. disable the alarm
3. alarm goes off after 3 minutes

**Expected Behavior:** Alarm not going off after 3 minutes when disabled.

**Actual Behavior:** Alarm going off after 3 minutes when disabled.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.
https://streamable.com/l67ph3

**Comment by Acheron420** [comment]
I have another house, does the same exact thing different location and everything. This time I didn't pull out a weapon, looted two cabinets and it got triggered again. I can provide the video if needed.

**Comment by Acheron420** [comment]
Also since we're on the topic of house robbery, the houses on the hills are way too hard to lockpick. 1 mistake = 1 picklock is broken. There is no reason for it to be that hard to picklock, just to get in and 2-3mins later the alarm going off.

**Comment by SurgeGit** [comment]
I agree and have made my own suggestion about alarms. Like I feel like with the testing I have done I feel like it is unintentional but then I have been told its intentional but it feels almost impossible that there is something your character could learn to prevent this from happening based on how fast/how little triggers it. Would love to see it tweaked or looked at to make it feasible to either 1. loot without the alarm going off straight away and/or 2. your char can learn how to prevent it going off so easily.

As for the lock picking I think the way it is right now is fine. These houses should be harder to pick and it is possible to get in without breaking one and the skill curve for lock picking means there is something to get good at in crime which is always a good thing.

**Comment by Acheron420** [comment]
I disagree on the part about the lockpicking; the difficulty is nice and all. But when the mechanic is based on randomness, it's not just "get good". There is 0 indication (the lock is marked with x, but that means nothing), which means you gotta get lucky since there is no room for messing up. IDK how long ago you tried pick-locking the houses on the hill, but it makes no sense for them to be this hard to lock-pick, and depending on nothing but luck. There is no pattern, there is no indication, there is no progression, just pure luck.

**Comment by SurgeGit** [comment]
I have and it is difficult but more than doable. It is skill based. There is no "luck"

**Comment by Acheron420** [comment]
@SurgeGit I would like you to explain how it's skill-based as I might be missing something.

Because the essence of a skill-based game mechanic is the player's ability to improve with practice, learning, and the development of strategies. If a mechanic relies entirely on guessing without hint or feedback, it cannot be called skill-based.
Skill implies the ability to apply knowledge and experience to achieve better outcomes. In this case, the system appears to operate entirely randomly. There's no discernible pattern to follow, no observable hints to guide the pick lock's angle, and success in one attempt does not guarantee success in the next (I pick-locked the door 3 times, and it still asked me to do it again).

If the mechanic were skill-based, one would expect consistency in outcomes related to player proficiency or improvement over time. The reality appears to rely more on a dice roll than applying the skill.

**Comment by SurgeGit** [comment]
You are missing something. Obviously I cannot say because that is meta. But it is skill based thats all I will say

**Comment by FlawwsX** [comment]
I guess the lack of notification was an issue. Now it informs you that the alarm is disabled temporarily.
