### ISSUE TITLE
(Prison) Doorway collision

### ISSUE THREAD

**Issue by Moonhera** [echoroleplay/feedback#17]
**Description:** When heading into 9B (solitary confinement cells), there are two accessible outdoor spaces. When you head to the doors, you are unable to head into them due to having a collision over the doorways. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Go into cellblock 9b
2. Unlock the door to the outside squares
3. Unable to go through

**Expected Behavior:** To be able to go into the confined outdoor spaces attached to 9B

**Actual Behavior:** Unable to go through. 

**Screenshot(s)/Video(s):** 
https://clips.twitch.tv/DependableArtsyPhoneYee-6vKtLMHg2l5eN307

**Comment by Stickerzz** [comment]
Fixed.
