### ISSUE TITLE
Turning radio off does not remove you from the radio

### ISSUE THREAD

**Issue by stayingquietnow** [echoroleplay/feedback#174]
**Description:** Turned the power off on my radio, and I am still showing on radio 1 on the MDT and can hear all radio traffic.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Use radio
2. Turn radio off
3. Still be connected to the radio

**Expected Behavior:** Turning the radio off should remove you from the radio and make you unable to hear radio traffic

**Actual Behavior:** Could still hear radio traffic and MDT shows me on channel 1

**Screenshot(s)/Video(s):** https://i.imgur.com/UOYPsO7.jpeg

**Comment by C4LLZ** [comment]
Was fixed
