### ISSUE TITLE
Hacker gets rep/svc as well after boost is completed

### ISSUE THREAD

**Issue by Sorrowvi** [echoroleplay/feedback#178]
**Suggestion Description**
[I think after the boost is complete the hacker that is registered on the boost should also receive rep and svc. If not just rep.]

**Reason**
Just makes it fair for both parties driver/hacker and they both get to eat.

**Comment by Britin123x** [comment]
If this isn't the case, it should be. Boosting is a 50/50 job and one party shouldn't get no rewards. Even if the argument is made that the look should be divied up and is a part of RP, not getting rep makes no sense in that context.

**Comment by FlawwsX** [comment]
According to the code, we unintentionally gave the leader the SVC the hacker should get.
```lua
exports.echo_phone:manageCrypto(leader, 'svc', rewardInfo.svc, true)
if hacker and hacker ~= 0 then -- Reward hacker same amount if exists.
    exports.echo_phone:manageCrypto(leader, 'svc', rewardInfo.svc, true)
end
```

**Comment by FlawwsX** [comment]
Furthermore, I have gone ahead and made it so the hacker is given reputation
