### ISSUE TITLE
Replace me with a brief and clear title describing the bug

### ISSUE THREAD

**Issue by jaaaxxxx** [echoroleplay/feedback#179]
**Description:** Unable to pay a bill from Dynasty 8 (tried fully restarting still unable)

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get a bill sent to you
2. try to pay the bill
3. Click the button and nothing happens.

**Expected Behavior:** Once you click "pay invoice," you should expect the money to be taken from your account.

**Actual Behavior:** No money was taken, and unable to pay the invoice, even when you have enough money. 

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1dXa6l44Oh4V3A/d1337aol2Q30?invite=cr-MSxuZ2QsMTY0MTE2ODk4LA

**Comment by BlueMistEMS** [comment]
I tested the issue myself, the issue seems to of resolved itself. I billed myself from the d8 account and everything worked properly as of this time stamp.

**Comment by jaaaxxxx** [comment]
It seemed to fix itself i got it rebilled. I will close it :)
