### ISSUE TITLE
Garage Scrip removing Extras and making helicopters spawn destroyed

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#18]
**Description:** Garage Scrip removing Extras and making helicopters spawn destroyed. Whenever you take out a vehicle from a garage all the extra cosmetics will be removed instead of saving from when you last pulled the vehicle out. In addition, It is impossible to fly helicopters due to this as their tail and rotor blades will be missing.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Store a vehicle with an extra turned on 
2. pull that same vehicle out

**Expected Behavior:** The extra you toggled on should stick and be on the car

**Actual Behavior:** it doesn't stick

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 
https://medal.tv/games/gta-v/clips/1bBtOl-5uGaqql/d1337CrbZtM7?invite=cr-MSxFSzYsMTc5NzI4NDkzLA

**Comment by davidxd33** [comment]
This should be fixed as of the latest restart.
