### ISSUE TITLE
Penthouse Garage is empty and phone doesnt show any of my vehicles

### ISSUE THREAD

**Issue by Vtek79** [echoroleplay/feedback#181]
Penthouse Garages have no cars in them plus phone doesnt show any vehicles

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Go to Garage and see cars
2. pull a car out of garage
3. Open phone to see where care are
4. Phone shows 2 cars i dont own and none of my other vehicles

Be able to pull out a car out of my penthouse garage, and also see on my phone my vehicles and where they are parked

Garage is empty and when i pull my phone out to see where my cars might be I dont see any of my vehichles 

https://cdn.discordapp.com/attachments/1110008385975353345/1118059877743476838/image.png

https://cdn.discordapp.com/attachments/1110008385975353345/1118059981464412240/image.png

**Comment by Vallenesca** [comment]
Same Garage as above - but Video! https://streamable.com/12tw8v
Before the 2am restart this issue occured as well. 
   --- A thought I had for this instance --- 
Could we be having an issue coz a Penthouse is owned, but the Garage says Apartment?
Although, that doesnt help that my vehicles are missing from my phone too..
