### ISSUE TITLE
(Prison) Changing

### ISSUE THREAD

**Issue by Moonhera** [echoroleplay/feedback#188]
**Suggestion Description**
 The ability to change clothing in the inmate in inmate arrivals (prison)

**Reason**
DOC and all inmates would benefit from this implementation as it would mean that DOC are safe taking people to change, people would be able to go straight into the prison from arrivals and it would keep that separated more effectively.

**Additional context**
Currently not able to change the inmates in inmate arrival when they come and have to take them up to the bathrooms in the old cafeteria space which meant we have to take them through the yard and delay the start of their sentence even further.  Inmates, if they get changed during their sentence, would also be able to do so in safety.  Inmates would also be able to use the bathroom.

**Comment by Astarner** [comment]
I've always thought the ability to change before going to prison should be a thing. Most people IRL don't show up to prison in street clothes. Adding a function to the police station and making the cops have criminals change before being delivered to prison would make most sense to me. That way DOC is free to watch over and not taking time to take a prisoner to change.

**Comment by C4LLZ** [comment]
Please give me a location for this. I'm not very familiar with the prison layout. 
You can do /copycoords on the location

**Comment by MToeltl** [comment]
vector3(1698.05, 2585.93, 45.89)

**Comment by C4LLZ** [comment]
Should be added withing a few restarts.
