### ISSUE TITLE
House Robberies Alarm

### ISSUE THREAD

**Issue by kaaycraay** [echoroleplay/feedback#199]
Upon doing a small house today I failed the hack to disable the alarm. No alarm went off when it happened. I went to my next house robbery after that to a big mansion in hills. I failed that hack and no alarm went off. However, I was stuck in the animation of hack.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get a job from linup
2. Go to house robbery
3. Do the hack.
4. Fail the hack

The alarm should be blaring in my ear.  Able to move around or out of the house.

No alarm sounding off. 
Getting stuck in animation hack

**Comment by kaaycraay** [comment]
Oddly weird but reattempted the small house n failed it purposely and the alarm went off.

**Comment by kaaycraay** [comment]
Was able to get into a tier 4 house today but no hack was given to disable alarm, so alarm went off.

**Comment by FlawwsX** [comment]
There is a chance the alarm doesn't go off. This is not a bug.
