### ISSUE TITLE
Weapon holstering is bugged

### ISSUE THREAD

**Issue by FiveMag** [echoroleplay/feedback#2]
## Bug Details

**Description:** <TEST> I am not able to holster my weapon. I can unholster it just fine but whenever i try to place it back, nothing happens.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Remove weapon from holster by pressing my hotkey.
2. Attempt to holster weapon by pressing the same hotkey,
3. Nothing happens. The weapon is now forever stuck in my hand as if i am Thor and this Glock is my Mjolnir Hammer.

**Expected Behavior:** I expect the weapon to go back into my holster.

**Actual Behavior:** The weapon does not go back into my holster and remains in my hand.

**Screenshot(s)/Video(s):** N/A

_Thank you for your contribution to our server. Your report is greatly appreciated and will help us to enhance the overall gaming experience._

**Comment by FlawwsX** [comment]
Is this a **REAL** issue?

**Comment by FiveMag** [comment]
It is NOT. I updated it with a "TEST" title but i guess it did not go through.

**Comment by FlawwsX** [comment]
Okay, hmph. I will mark this not as a bug and close the issue.
