### ISSUE TITLE
A change to crime/how crime is done

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#208]
**Suggestion Description**
So i am going to start this with saying i don't mean to shit on anyones RP if it comes across as that.

I feel like with the current method of how to get items for crime is done we are very gatekept by 1 person, as we know for Thermite there is no way to craft this and as for other devices eg boosting etc there has been no confirmed on the way to get these other than the original way which was again locked behind the same person, i feel like the following should be done.

(Before you say have to you tried breaking into stuff, yes our group does various jobs and still nothing)

Boosting - Currently the way to apparently receive this doesn't make much sense, lots of people love boosting as it is a smaller crime but can give some fun chases. I feel like this device should be buyable through the racing scene either using SVC or Cash.

Thermite - Yes you hate crafting we get it, so why not trading? Multistep process in which you go to various areas across the map trading one thing for another and so on until you get the termite at the last step.

**Reason**
Currently feels like crime is very locked behind 1 person

**Comment by KomitDzn** [comment]
I 100% agree with this, as a crim who is no longer in a gang and doesn't have connections to a ton of people, I used to still be able to do crime whenever. Now, only people who are more known even have a chance of getting everything, like I cant even boost which is what i loved doing. There is no motivation for the majority of crims because there is nothing you can do now nor any way to work your way to doing it other than just standing around. This may promote more civ-like RP which is good, but at the same time isn't because a lot of people enjoy criminal activities. This has even made cop start to get boring as there is less and less crime to respond to, and now it feels like all you can do are traffic stops and drug calls, when I feel like I'd like to respond to the occasional fleeca or DT, however that just doesn't happen anymore.

**Comment by rreplay** [comment]
Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.

**Comment by rreplay** [comment]
Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.

**Comment by SuspiciouslyStickySock** [comment]
> Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.

Okay first lets not attack him as i said i do not want to attack/shit on someones RP. Add so context/suggestions etc to this do not comment just to be a dick

**Comment by Lane2G** [comment]
I miss working up the food chain through jobs, now I can  buy a PAC or paleto starter pack makes 0 sense

**Comment by Lane2G** [comment]
> Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.

I think lambs intentions are sound and it’s 100% approved through the staff I just am not a fan of how it’s being handled. Let’s not attack people

**Comment by damightylamb** [comment]
> Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.

Lol

**Comment by damightylamb** [comment]
> Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.

You say I don't know the crim world at all when I helped fsm build their black market, played crime for most of my rp career, and did all the development for 90% of the crime in the server. 

I'm not going to entertain this comment anymore because it's ignorant.

**Comment by SuspiciouslyStickySock** [comment]
> > Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.
> 
> Lol

Maybe the Mighty Lamb can give some thoughts onto things. Like i said at this time it feels like the progression of stuff is very hindered or at least that is how it feels.

Boosting is a much loved crime by so many people but yet the only boosting devices out there are the ones given out by you and they are going bad.

Thermite is only obtainable through you which i don't think makes sense, there is already a BM within the server so why is it through you and not them? 

If you disagree with us please provide us with why

**Comment by rreplay** [comment]
> > Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.
> 
> Okay first lets not attack him as i said i do not want to attack/shit on someones RP. Add so context/suggestions etc to this do not comment just to be a dick

Sure, he should have a group of people and they should have real meetings with groups where they talk about there ambitions in the city and what they want to angle themselves as, possibly to become plugs themselves, or to hit jobs or do whatever, because taking away crafting and just giving out to whoever gets replied to on Twitter makes no sense

**Comment by damightylamb** [comment]
> > > Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.
> > 
> > Lol
> 
> Maybe the Mighty Lamb can give some thoughts onto things. Like i said at this time it feels like the progression of stuff is very hindered or at least that is how it feels.
> 
> Boosting is a much loved crime by so many people but yet the only boosting devices out there are the ones given out by you and they are going bad.
> 
> Thermite is only obtainable through you which i don't think makes sense, there is already a BM within the server so why is it through you and not them? 
> 
> If you disagree with us please provide us with why

Boosting can be obtained not through me. I only handed out a few in the beginning before the new way to get the devices was implemented. 

Thermite selling was on hold for a few days because people stock piled them when they were hoarding them from crates.

I have changes planned to make it more inclusive for all crims. I just want to see crafting bs.

**Comment by Lane2G** [comment]
> > > Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.
> > 
> > 
> > Lol
> 
> Maybe the Mighty Lamb can give some thoughts onto things. Like i said at this time it feels like the progression of stuff is very hindered or at least that is how it feels.
> 
> Boosting is a much loved crime by so many people but yet the only boosting devices out there are the ones given out by you and they are going bad.
> 
> Thermite is only obtainable through you which i don't think makes sense, there is already a BM within the server so why is it through you and not them?
> 
> If you disagree with us please provide us with why

I chopped everything up to growing pains but it’s clear this is how it’s intended to be designed. No crims are happy with it at the moment. The most Ideal thing for lowering the amount of crim naturally was Moving the thermite bench more then one time a year, making it so the hacks weren’t able to cheated on. Instead it now feels like Progression on every level has died. New crims can’t make connections Veterans of the server are just stuck waiting for a call to buy a job.

**Comment by SuspiciouslyStickySock** [comment]
I think thermite shouldn't be locked behind you sadly and my reason is nothing more than availability and requirement of needing thermite for jobs. We need more way to obtain thermite.....

If boosting devices are obtained through the way everyone believes them to be this also does not make sense to the device itself.

**Comment by KomitDzn** [comment]
> > > > Lamb just wants his ego stroked, he does 0 rp when he does meet up with people, makes no sense why a cop main should run crime, when he isn’t even in the gang leaders discord, or honestly knows the crim world at all. Just frustrating and doesn’t make sense at all.
> > > 
> > > 
> > > Lol
> > 
> > 
> > Maybe the Mighty Lamb can give some thoughts onto things. Like i said at this time it feels like the progression of stuff is very hindered or at least that is how it feels.
> > Boosting is a much loved crime by so many people but yet the only boosting devices out there are the ones given out by you and they are going bad.
> > Thermite is only obtainable through you which i don't think makes sense, there is already a BM within the server so why is it through you and not them?
> > If you disagree with us please provide us with why
> 
> I chopped everything up to growing pains but it’s clear this is how it’s intended to be designed. No crims are happy with it at the moment. The most Ideal thing for lowering the amount of crim naturally was Moving the thermite bench more then one time a year, making it so the hacks weren’t able to cheated on. Instead it now feels like Progression on every level has died. New crims can’t make connections Veterans of the server are just stuck waiting for a call to buy a job.

Reflecting on how crime was, I honestly think the real issue with crime was actually store robberies. I think everything else was fine, but a constant hostage situation every 30 minutes because people are hitting a store was the real issue with hostage situations. The cooldowns of like an hour and a half between vangies which is now two hours and similar for fleecas which were one hour (at least I think, this is just from a pattern recognition standpoint) has helped a bit as well, but might be too much of a cooldown. I also agree with everything else said but imo everything was run perfectly before BUT store robberies.

**Comment by damightylamb** [comment]
They are not obtained by anyone besides a script.

**Comment by KomitDzn** [comment]
> They are not obtained by anyone besides a script.

they as in the boosting device?

**Comment by damightylamb** [comment]
Correct

**Comment by SuspiciouslyStickySock** [comment]
> They are not obtained by anyone besides a script.

This is not what i mean? I guess i can say it as if used it is meta but currently the thought/belief is the Malicious USB used for boosting is obtained through houses, i think if that is correct than it should be changed. Boosting should work alongside the racing scene in my opinion the device should be purchasable for SVC/cash through the racing scene for example

**Comment by rreplay** [comment]
> Correct

They are given out at the end of certain races too, wym by just a script

**Comment by damightylamb** [comment]
> > Correct
> 
> They are given out at the end of certain races too, wym by just a script

Maybe go find out instead of trashing me in here

**Comment by KomitDzn** [comment]
> > They are not obtained by anyone besides a script.
> 
> This is not what i mean? I guess i can say it as if used it is meta but currently the thought/belief is the Malicious USB used for boosting is obtained through houses, i think if that is correct than it should be changed. Boosting should work alongside the racing scene in my opinion the device should be purchasable for SVC/cash through the racing scene for example

10000% agree

**Comment by damightylamb** [comment]
> > They are not obtained by anyone besides a script.
> 
> This is not what i mean? I guess i can say it as if used it is meta but currently the thought/belief is the Malicious USB used for boosting is obtained through houses, i think if that is correct than it should be changed. Boosting should work alongside the racing scene in my opinion the device should be purchasable for SVC/cash through the racing scene for example

Not everyone who wants to boost races. And not everyone who races wants to boost

**Comment by SuspiciouslyStickySock** [comment]
It makes more sense for them to be obtained in that scene rather than houses is my thought

**Comment by KomitDzn** [comment]
> > > They are not obtained by anyone besides a script.
> > 
> > 
> > This is not what i mean? I guess i can say it as if used it is meta but currently the thought/belief is the Malicious USB used for boosting is obtained through houses, i think if that is correct than it should be changed. Boosting should work alongside the racing scene in my opinion the device should be purchasable for SVC/cash through the racing scene for example
> 
> Not everyone who wants to boost races. And not everyone who races wants to boost

and if they are from houses not everybody that boosts wants to rob houses and vice versa? I feel like the racing scene just makes much more sense

**Comment by Lane2G** [comment]
> 

But to boost you need crazy amounts of stuff tied to racing

**Comment by rreplay** [comment]
> > > Correct
> > 
> > 
> > They are given out at the end of certain races too, wym by just a script
> 
> Maybe go find out instead of trashing me in here

Literally confused because your comment on by a script doesn’t make sense, because they have been given out as racing rewards to multiple ppl I know

**Comment by Lane2G** [comment]
> > > They are not obtained by anyone besides a script.
> > 
> > 
> > This is not what i mean? I guess i can say it as if used it is meta but currently the thought/belief is the Malicious USB used for boosting is obtained through houses, i think if that is correct than it should be changed. Boosting should work alongside the racing scene in my opinion the device should be purchasable for SVC/cash through the racing scene for example
> 
> Not everyone who wants to boost races. And not everyone who races wants to boost

But to boost you need crazy amounts of stuff from racing.

**Comment by KomitDzn** [comment]
> 

i think the more important part is to not meta that info :)

**Comment by damightylamb** [comment]
> > > > Correct
> > > 
> > > 
> > > They are given out at the end of certain races too, wym by just a script
> > 
> > Maybe go find out instead of trashing me in here
> 
> Literally confused because your comment on by a script doesn’t make sense, because they have been given out as racing rewards to multiple ppl I know

And I'm telling you they can be obtained in a different way. You would think the dev would know. So go and find out

**Comment by rreplay** [comment]
> > > > > Correct
> > > > 
> > > > 
> > > > They are given out at the end of certain races too, wym by just a script
> > > 
> > > 
> > > Maybe go find out instead of trashing me in here
> > 
> > 
> > Literally confused because your comment on by a script doesn’t make sense, because they have been given out as racing rewards to multiple ppl I know
> 
> And I'm telling you they can be obtained in a different way. You would think the dev would know. So go and find out

That wasn’t my issue with your statement, but ok.

**Comment by FlawwsX** [comment]
We’re working to improve the way crime items obtain. We love your feedback and are always open to it. But, there’s a line that cannot be crossed and those that do cross that line will be dealt with.

Thank you for your contributions and we will take on board your feedback.
