### ISSUE TITLE
Big Pawn peds not showing a sell/trade option.

### ISSUE THREAD

**Issue by Bakr8724** [echoroleplay/feedback#21]
**Description:** Started a route from big pawn, was given a car + destination. Once I've arrived, the npc is there, but no option to sell/trade.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Talk to big pawn local
2. get in the car and make your way to the destination.
3. Attempt to trade/sell to local.

**Expected Behavior:** Should be able to sell/trade at the destination.

**Actual Behavior:** No option is showing up to trade/ sell.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 

![Screenshot (16)](https://github.com/echoroleplay/feedback/assets/114519178/de4b960e-e9cd-42e5-9264-1d8c3620da02)

**Comment by davidxd33** [comment]
The issue has been found and a fix has been deployed for the next restart. Thank you.
