### ISSUE TITLE
Link Up App

### ISSUE THREAD

**Issue by brownbag13** [echoroleplay/feedback#210]
**Description:** Please **replace me** with a description of the bug in as much detail as possible.
The queue spams "we found a job for you but you either have too many or too less members" once you hit a job, leave the group, and try to hit a house.
**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Hit a job in a group
2. Leave the group after the job
3. Queue up for a house robbery and get spammed with "we found a job for you but you either have too many or too less members"

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.
Be able to leave the group and the app recognize you by yourself.
**Actual Behavior:** Describe what actually happened instead.
App still thinks i am still in a big group
**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

https://github.com/echoroleplay/feedback/assets/135925876/4368f645-fe3d-4529-9065-48786997ecb1

**Comment by FlawwsX** [comment]
It's possible you were on cooldown and the final group count was 0 after our checks checked the group members' cooldown status.

I have added a check for this to give you an appropriate message.
