### ISSUE TITLE
24/7 Store Stash 

### ISSUE THREAD

**Issue by 0wv** [echoroleplay/feedback#212]
**Suggestion Description**
Have the stash for holding the things you are selling in your store, act like a fridge so food/drinks don't go bad quick! 

**Reason**
In stores you have freezers that hold the food in, so this is the closest to it for selling food and drinks :)

**Additional context**
Saves people from buying moldy food.

**Comment by karichandesu** [comment]
If you own a store, you should be on top of it and making sure that your store has fresh food and supplies for people to buy every day.

**Comment by 0wv** [comment]
> 

Sure, but If im away for a day it's all going bad. It makes sense but in terms of QOL it's super annoying.

**Comment by karichandesu** [comment]
Hire people.

**Comment by C4LLZ** [comment]
This would take too much RP away from actual restaurants.  If you want to buy food and sell it at your store you should have to get it fresh and not have a stock of it.
