### ISSUE TITLE
Weevil has a license plate that does not match the phone app after customization

### ISSUE THREAD

**Issue by sixhundrednuts** [echoroleplay/feedback#213]
**Description:** Weevil has a license plate that does not match the phone app after customization

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Purchase a Weevil
2. Take it to be customized
3. Store to save customizations
4. Pull out vehicle and notice new license plate

**Expected Behavior:** Plate does not change

**Actual Behavior:** Plate is replaced by one that looks like a custom plate 

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.
https://cdn.discordapp.com/attachments/703738305120043082/1119113262605291660/image.png
https://cdn.discordapp.com/attachments/703738305120043082/1120798670401585213/image.png

**Comment by davidxd33** [comment]
Is this still an issue @sixhundrednuts?

**Comment by sixhundrednuts** [comment]
The wipe took the car so no? Might be in the future but I haven’t gotten the car back to test @davidxd33

**Comment by davidxd33** [comment]
`ALAN__0` plates are the default fallback plate for GTA when an invalid plate name is assigned, possible something weird was happening with a custom plate at the time although this is triaged for a rework soon.
