### ISSUE TITLE
Cannot pick up photography lights after you put them down

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#214]
Cannot pick up photography lights after you put them down

**Reproduction Steps:** 
1. Put down a photography light
2. Try and pick it up with your F6 targeting mode (3rd eye)

**Expected Behavior:** Gives you a prompt to pick it up

**Actual Behavior:** no prompt pops up to pick it up

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1f43HktHWETcNz/d1337W5U6fYd?invite=cr-MSxScUksMTc5NzI4NDkzLA

**Comment by StuxxyOfficial** [comment]
I took a brief look, but it seems the intended behavior is to place the prop and pickup it up with the 6 key. So i don't believe this is a bug, but potentially an enhancement.

**Comment by C4LLZ** [comment]
Not a bug, Pick up with 6 key
