### ISSUE TITLE
Invisible trees at legion square (not because of texture loss) 

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#215]
**Description:** Invisible trees at legion square (not because of texture loss) 

**Reproduction Steps:**
1. Go to the east side of legion square on Strawberry Ave
2. Drive on the tree planters

**Expected Behavior:** no collisions

**Actual Behavior:** There is collisions

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1feu4PnxjIyGDJ/d1337jjn6N7K?invite=cr-MSxXUnosMTc5NzI4NDkzLA

**Comment by Stickerzz** [comment]
Fixed now
