### ISSUE TITLE
(Prison) Jailbreak reset button

### ISSUE THREAD

**Issue by Moonhera** [echoroleplay/feedback#22]
**Description:** When the jailbreak goes off, the only way to stop it is the alarm is to reset the doors. When pressing the jailbreak reset button it unlocks all the doors in the prison apart from the front lobby building

**Reproduction Steps:**  
1.  Press the jailbreak button
2.  Go to the jailbreak reset button. 
3.  Press the button. 

**Expected Behavior:** Reset jailbreak button should not unlock exterior doors to the outer road perimeter nor to the inmate arrivals but open all the other doors. 

**Actual Behavior:** It opens all the doors inside the main body of the prison (apart from the lobby building. 

**Screenshot(s)/Video(s):**

**Comment by damightylamb** [comment]
This has been pushed for restart
