### ISSUE TITLE
Move the vehicle rental at Beeker's Paleto

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#220]
**Suggestion Description**
Move the Vehicle rental at Beeker's 

**Reason**
Currently the rental spot that just got implemented at Beeker's is in an annoying spot I guess to put simply as the pullout blip is right in front of the store front door and the vehicle put away spot is in front of the garage as seen by the pictures attatched. With that, It would be way better if it was moved over near the gas station area as indicated by the pictures below

**Additional context**
Reason I made the suggestion is that as a CEO of the shop its super annoying that it is right in front of the doors and has such a massive blip

![06_23_2023 - SS3009](https://github.com/echoroleplay/feedback/assets/134963542/770b9b69-297f-4c6a-9ad2-d6549413e133)

![06_23_2023 - SS3010](https://github.com/echoroleplay/feedback/assets/134963542/1fa70e60-0750-4e89-873f-79b6876b4b91)

Possible new area:
![06_23_2023 - SS3012](https://github.com/echoroleplay/feedback/assets/134963542/5cb0ad8e-426c-44d7-8a3b-4816e7a7bbd9)

**Comment by C4LLZ** [comment]
Changed
