### ISSUE TITLE
Debug Zone still active for fuel station

### ISSUE THREAD

**Issue by Balla44** [echoroleplay/feedback#221]
**Description:** It appears as though the debug zone is still active for fueling at the gas station at the corner of el rancho and capital. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. grab nozzle
2. observe debug fueling zone

**Expected Behavior:** Not see debug zone

**Actual Behavior:** saw debug zone

**Screenshot(s)/Video(s):** ![image](https://github.com/echoroleplay/feedback/assets/109919130/c0193152-fbb7-4997-8da5-4c8685fb15e3)

**Comment by C4LLZ** [comment]
Unsure if this is something that was added because people could not find it or not. Will check :) Maybe @damightylamb knows?

**Comment by davidxd33** [comment]
This was done intentionally to give a visual cue.
