### ISSUE TITLE
Boosting Queue Bug

### ISSUE THREAD

**Issue by brownbag13** [echoroleplay/feedback#228]
**Description:** Boosting Queue bugs out and stops giving out jobs

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Queue up for a boost
2. Never receive one until server reset
3. Accept boost and it's all good. 

**Expected Behavior:** Queue to consistently hand out jobs throughout the storm. 

I have no clue why it does this, just want you guys to be aware of the problem.

**Actual Behavior:** Queue bugs out for some reason and stops giving jobs out. 

**Screenshot(s)/Video(s):** None.

**Comment by FlawwsX** [comment]
Resolved
