### ISSUE TITLE
Hospital MLO

### ISSUE THREAD

**Issue by LittleCatnee** [echoroleplay/feedback#245]
**Suggestion Description**
I am suggesting the Hospital https://forum.cfx.re/t/ocean-medical-center-mlo-building/4843997. It is a HUGE hospital which could enforce more roleplay! There is multiple patient rooms, surgery rooms and more. This is just a suggestion, as the current hospital is amazing as well but I've seen somebody else in our community think that this is maybe a good idea. I'd like for you to at least have a look at it! 

**Reason**
It can enforce more roleplay, including medical and more. There is a Vets Office where K9's could be treated, as well as a Pharmacy and more. More can be found on the website linked to the Request!

**Additional context**
![image](https://github.com/echoroleplay/feedback/assets/138127270/0a7bdd19-4b29-404f-ba20-e105f5be2089)
![image](https://github.com/echoroleplay/feedback/assets/138127270/cedce923-aa13-4d67-b358-98db5d6e4f95)
![image](https://github.com/echoroleplay/feedback/assets/138127270/6ad5e6e8-d42d-4410-8122-4e2980b746ba)
![image](https://github.com/echoroleplay/feedback/assets/138127270/69ae5a29-22aa-4b9a-ac4a-45f77acf7098)
![image](https://github.com/echoroleplay/feedback/assets/138127270/37c62ec4-b915-47b5-9fed-7a3dad8f662b)
![image](https://github.com/echoroleplay/feedback/assets/138127270/1eb820fc-8ed7-4905-a522-ffc5cb8b9b28)
![image](https://github.com/echoroleplay/feedback/assets/138127270/cbc8ffa0-165f-4da1-879e-8293e51b27ac)
![image](https://github.com/echoroleplay/feedback/assets/138127270/2cdacf91-dc4c-4563-a127-597df26c6e3f)
![image](https://github.com/echoroleplay/feedback/assets/138127270/fc2ef19b-d7b8-4c61-8275-946c09ae5ece)
![image](https://github.com/echoroleplay/feedback/assets/138127270/b93f4df4-789c-4413-9be3-4ed6d8f1b662)

**Comment by FlawwsX** [comment]
We don't need such a big hospital, sorry
