### ISSUE TITLE
NVE not working on restart

### ISSUE THREAD

**Issue by candixbaconn** [echoroleplay/feedback#25]
**Description:** Logged into the server and NVE shaders arent working 

**Reproduction Steps:** 
1. Log in
2. See issue on character select screen

**Expected Behavior:** NVE shaders should work.

**Actual Behavior:** When shaders are applied I get this black and white effect on my screen

**Screenshot(s)/Video(s):** https://imgur.com/Qu2MVoZ

**Comments:** I only have NVE and reshade installed. Unsure if there is a correlation. Theres no error in the F8 log.

**Comment by FlawwsX** [comment]
This is not an EchoRP bug, please use our support section to find out how to fix this.
