### ISSUE TITLE
Remove tax on withdrawing/depositing cash

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#251]
**Suggestion Description**
Remove the tax related to withdrawing/depositing your own money, doesn't make any sense

**Reason**
Why are we being taxed on our own money, if i want to take out 2k for something i actually end up losing an extra like 200$ for no reason

**Additional context**
[Add any other context (such as why you made this suggestion) or screenshots about the feature request here.]

**Comment by C4LLZ** [comment]
This has been changed. And changes are med every day to ensure a stable econ. Is there anything else you want to add or are we good to close?
