### ISSUE TITLE
Replace with a brief and clear title describing the feature

### ISSUE THREAD

**Issue by Balla44** [echoroleplay/feedback#255]
**Suggestion Description**
Move/ Add Car Rental

**Reason**
I don't think we necessarily need everyone to have a free Alta apartment but the car rental spot being there is a bit out of place now. Adding or moving the car rental spot to one of the current spawn points (namely bus station)  would bring a huge improvement to QOL and also make RP sense.

**Comment by purpleferretz** [comment]
i think it would be neat if the car rental location in the city was at PDM

**Comment by TomatenCas** [comment]
closing this as there's a suggestion like this already
