### ISSUE TITLE
Mechanics: Liveries & Extras not persistant

### ISSUE THREAD

**Issue by hatchett0001** [echoroleplay/feedback#26]
**Description:** A few people have come to CNC Harmony, mentioning the liveries for their vehicles are no longer on the vehicle, as well as extras not staying as they were chosen.  We put the DOC liveries on their Crown Vics and they went to the garages, stored & pulled them back out with no liveries & extras being different (such as the additional lights, back seats, etc) & the Crewcab flatbeds not having their CNC livery.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Place sticker/extra
2. Finish, store vehicle to apply the changes
3. pull vehicle out, changes gone

**Expected Behavior:** The changes to stick.

**Actual Behavior:** Don't stick.

I haven't seen this mentioned elsewhere, or brought up by any other mechanics, so, I'm not certain how wide-spread it is.

**Comment by CadillacKoopa** [comment]
same with my Corsita

**Comment by CadillacKoopa** [comment]
it's actually all cars. at least all of my IC wife and I. we have around 40 cars combined

**Comment by CadillacKoopa** [comment]
![Screenshot 2023-05-30 002458](https://github.com/echoroleplay/feedback/assets/76125478/b85f2ed7-c42c-4160-a8ba-1e53db9c3b12)
