### ISSUE TITLE
Return prison income and keep time removal for prison jobs

### ISSUE THREAD

**Issue by LordRusch** [echoroleplay/feedback#261]
**Suggestion Description**
[Return the income to the prison jobs, keep the ability to remove time as well.]

**Reason**
[Jail Food has increased in price and lifers and inmates have no way of making money at all. Keeping the decrease in time from jobs would also help appeal to those who just want to steer clear of the violence in the prison and get back out as well as make those super long sentences more bearable.]

**Additional context**
[Recent update has made an increase for jail food cost due to people coming in and getting the $1 jail food instead of going to restaurants and purchasing foods from there.  The Big Update from May/June had changed the prison jobs from providing an income to decreasing sentences by performing the job tasks.]

**Comment by Ponnkun** [comment]
This has been addressed and jobs have a small chance to give income.
