### ISSUE TITLE
Map not working correctly in the esc. menu

### ISSUE THREAD

**Issue by felixqueb** [echoroleplay/feedback#265]
**Description:** When going onto the map in the esc. menu, I can't go to the bottom of the map. When I go over a blip, ie: a cop blip, it does not show up. When i try to place a point down, it marked a random crime, even if I am at the opposite side of the map. When Using the list on the right side, no matter what I do, it always goes back to a random crime.  It goes back to normal when I turn my transponder off. I tried to disable as many blip as possible, but only the transponder help. 
 
**Reproduction Steps:** 
1. Press escape
2. open the map
3. try to ping or go over anything. 

**Expected Behavior:** being able to ping different blips and/or being able to know what is the blip. 

**Actual Behavior:** a random crime is being ping

**Comment by davidxd33** [comment]
If the amount of blips in your map key legend is at 99, you have reached the blip limit and should turn some blips off in the F1 menu.

**Comment by felixqueb** [comment]
Like I said, I disabled almost everything I could. I

**Comment by felixqueb** [comment]
I just tried with everything disabled, I have the same issue with the transponder on. Not to sure what else to do

**Comment by davidxd33** [comment]
Please show a screenshot of you map and key legend
