### ISSUE TITLE
Gap in fence up in the prison

### ISSUE THREAD

**Issue by LordRusch** [echoroleplay/feedback#269]
**Description:** There is a gap in the fence between Cellblock 4 and the Solitary building 9B.

**Reproduction Steps:** 
1. Hug tight to the wall of Cellblock 4
2. Look at the fence and press "Q"
3. Hug the wall and go passed the fence.

**Expected Behavior:** The fence was placed to block inmates from leaving the yard.

**Actual Behavior:** A gap just large enough that people will actually sneak through, making DOC have to search around the North yard.

**Screenshot(s)/Video(s):** picture of the area, courtesy of Lyra
![y83bnabn](https://github.com/echoroleplay/feedback/assets/138604604/33954761-5ed6-4ba4-a491-66f1b95fb1a7)

**Comment by ook3D** [comment]
will be taken care of shortly

**Comment by ook3D** [comment]
should be fixed, make another issue if you find anymore 👍
