### ISSUE TITLE
Typo on Radios

### ISSUE THREAD

**Issue by Brandos3** [echoroleplay/feedback#27]
**Description:** The new radios have 2 volume up buttons. They work as intended, but they both say volume up. Just a typo in the design.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Look at volume buttons on radio. 
2. Notice the bottom one that should say volume down says volume up.
3. ...

**Expected Behavior:** Volume down button should say volume down.
**Actual Behavior:** Volume down button says volume up.

**Screenshot(s)/Video(s):**  

https://i.imgur.com/ub8sMrf.png

**Comment by Ponnkun** [comment]
Will close after pull.
