### ISSUE TITLE
Weazel News Cameras Not Working

### ISSUE THREAD

**Issue by PrincessMilky** [echoroleplay/feedback#270]
**Description:** Weazel News Cameras not working, currently unusable (have not been working since March 2023)

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
Step 1. Get a camera from the Weazel store
Step 2. Try to use the camera
Step 3. Camera won't work and there is no popup menu to switch between camera options (news, blackbars, etc.)

**Expected Behavior:** Using the camera will usually give you options for camera options such as to put a news filter or movie filter. Essentially you should be able to use the camera however we cannot at this time.

**Actual Behavior:** Nothing happens. It won't use the item but says its used like when you use any item

**Comment by C4LLZ** [comment]
Should be resolved shortly
