### ISSUE TITLE
House Robbery Interior issue

### ISSUE THREAD

**Issue by oGChRoMa** [echoroleplay/feedback#28]
**Description: House robberies, bad interior. One of the new house interiors has you walk into an apartment-type house, you have 3 doors in front of you with the security pad on your left. The room on the right is a bedroom, the room on the left is a laundry/washroom, and the room straight ahead of you is a living area / kitchen. This house if you attempt to do the hack on the security to disable it, kicks you out of the house because the security pad is placed to close to the door which causes you to exit the house while flexing your E muscle to do the hack. This also causes you to float in place and get stuck, which causes you to have to take a quick nap.

**Reproduction Steps:
1. Start a house robbery, and have the interior stated above.
2. Try to disable the security with your hacking device.
3. Flex your E muscle to perform the QTEs and get kicked out of the house.

**Expected Behavior: You perform the hack and disable the security

**Actual Behavior: You get kicked out of the house which causes you to get stuck and fail the QTE which sets the alarm off.

**Screenshot(s)/Video(s):**[ If possible, add screenshots or videos to help explain your problem. ](https://cdn.discordapp.com/attachments/820832747441487882/1112995425658601503/image.png) This is the interior in question.

**Comment by Morphiushell** [comment]
In addition to this when attempting the hack and being kicked out of the house it brings you back into the house where you cant search anything and you also can not leave the house without logging out the server. I went into a hous today and some poor guys was in there he said he had been stuck there for over an hour

**Comment by FlawwsX** [comment]
This has been resolved.

**Comment by oGChRoMa** [comment]
I don't know if it's because it hasn't been pushed yet. However I still had this issue today.
