### ISSUE TITLE
LinkUp app queuing issue

### ISSUE THREAD

**Issue by oGChRoMa** [echoroleplay/feedback#29]
**Description:** Slight issue with the house robberies LinkUp queuing system. Earlier I was in a queue for 6hrs stuck at position 3/150~ not moving. So I decided to leave the queue and rejoin it. Upon doing this I was given the message "You are already on job" within the linkup application, however, I never even did a job.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Not sure what caused it intially
2. Leave queue once it seems to be stuck
3. Attempt to rejoin

**Expected Behavior:** Rejoin the queue

**Actual Behavior:** Got the message "You are already on job"

**Comment by Ponnkun** [comment]
Hello @oGChRoMa,

Do you have a screenshot of your F8 console by any chance or any video of this happening?

**Comment by FlawwsX** [comment]
This was resolved.
