### ISSUE TITLE
MK18 showing while spectating, even after deleting the object via F10

### ISSUE THREAD

**Issue by Kwamer** [echoroleplay/feedback#3]
## Bug Details

**Description:** Please describe the bug in as much detail as possible. Explain what you expected to happen and what actually happened. If you encountered an error message, please include it here.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Have an MK18 (modified by weapon bench)
2. Delete the prop via F10 "delete object"
3. NoClip/Magic Trick - prop can still be seen.

**Expected Behavior:** Weapon not to be shown.

**Actual Behavior:** Weapon shows with above repro steps.

**Screenshot(s)/Video(s):** N/A, can get if needed.

**Comment by FlawwsX** [comment]
Hello!

This is not really a bug, but rather something we did not consider with the new weapons on back. I will work to add spectate support soon.

**Comment by FlawwsX** [comment]
This has been resolved.
