### ISSUE TITLE
Cannot exit the penthouse garage

### ISSUE THREAD

**Issue by xfurykill** [echoroleplay/feedback#30]
You are unable to leave the garage in the penthouse. If you use E to exit sometimes works, sometimes doesn't. When it doesn't it puts you in another instance thinking you left the building. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Enter garage
2. use E to exit
3. you are stuck in the garage

**Expected Behavior:** to leave the penthouse garage

**Actual Behavior:** you cannot leave

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 

https://cdn.discordapp.com/attachments/1037521320889565294/1111812930682486784/2023-05-27_01-25-05.mp4

**Comment by davidxd33** [comment]
> You are unable to leave the garage in the penthouse. If you use E to exit sometimes works, sometimes doesn't. When it doesn't it puts you in another instance thinking you left the building.
> 
> **Reproduction Steps:** Clearly describe the steps to reproduce the bug.
> 
> 1. Enter garage
> 2. use E to exit
> 3. you are stuck in the garage
> 
> **Expected Behavior:** to leave the penthouse garage
> 
> **Actual Behavior:** you cannot leave
> 
> **Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.
> 
> https://cdn.discordapp.com/attachments/1037521320889565294/1111812930682486784/2023-05-27_01-25-05.mp4

Please attach a screenshot of your F8 the next time this happens.

**Comment by davidxd33** [comment]
Please attach a screenshot of your F8 the next time this happens.

**Comment by xfurykill** [comment]
@davidxd33 I used F8 in the clip I attached

**Comment by davidxd33** [comment]
> F8 the *next time* this happens.

**Comment by xfurykill** [comment]
![image](https://github.com/echoroleplay/feedback/assets/80468889/9a8729e2-3b65-4b90-9191-9a5a5be2e50d)
 here you go

**Comment by xfurykill** [comment]
![image](https://github.com/echoroleplay/feedback/assets/80468889/e4a1c91c-4324-4a9c-9956-7e72b2571857)

and then this is me tryna get back into the garage after leaving through the apartment lift. it thinks it put me back in the garage but i'm invisible to all players and they're invisible to me

**Comment by davidxd33** [comment]
Any other information? How did you enter the garage, through street or lif? Does this happen only when you leave in a vehicle or by foot?

**Comment by xfurykill** [comment]
when i enter the garage by foot, its fine i can leave ands exit and it have no issues. It seems to mainly be when a vehicle is involved! via the street. the first time i did this with a car i parked and left the car there, got stuck, left via the lift and when i re-logged my vehicle said it was parked int he penthouse garage and it wasnt there

**Comment by davidxd33** [comment]
This may be potentially fixed at the next restart, please let us know of any results.

**Comment by xfurykill** [comment]
seems to be working fine now! Thanks! <3
