### ISSUE TITLE
Link-Up Job Pop-Up disappeared when you get a number send to you

### ISSUE THREAD

**Issue by MrsTORN** [echoroleplay/feedback#31]
**Description:** When I was ready for a Link-Up Job, I got sent a phone number while the Link-Up Pop Up message was there and the 'phone number' message removed the Link Up Job Message and still says i already have a job ready but I can't see anything on the gps.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get a Link-Up job to be ready to get accepted that has popped up on your phone
2. Someone sends you their phone number while the Link Up Pop-Up is ready to be accepted
3. ...

**Expected Behavior:** I expected to accept the phone number and then the link-up message would still be there.

**Actual Behavior:** The phone number message deleted the Link Up pop up message, stopping me from actually accepting it

**Screenshot(s)/Video(s):
![Screenshot_11](https://github.com/echoroleplay/feedback/assets/59653371/34f75558-7556-4785-9291-17b2f744ca9b)

![Screenshot_13](https://github.com/echoroleplay/feedback/assets/59653371/ba75de6f-f92b-4198-9595-6b2eb297599b)

**Comment by FlawwsX** [comment]
This was fixed as a result of another fix.

There was no timeout on the server->client callback, but now there is :P
