### ISSUE TITLE
Von Crastenberg Stash Bug

### ISSUE THREAD

**Issue by rso25** [echoroleplay/feedback#310]
**Description**
Last time I was in the server I had flew out in my apartment with my door locked - not sure about stash. I flew back in just now, opened my stash, and it was empty(aside from a few basic items). I am unsure what to do and how this was even possible. It might have been that somone bugged into my apartment or opened my stash through a wall. I am not 100% sure however.

**Reproduction Steps:**
1. Own Motel
2. Populate stash with items
3. Third-eye through wall - where stash would be
4. Open stash
5. Take items

**Expected Behavior:** 
Not be able to be looted through a wall.

**Actual Behavior:**
Can loot items through wall.

**Screenshot(s)/Video(s):**
![bug](https://github.com/echoroleplay/feedback/assets/138974765/645c0185-fbd8-4f7a-9431-e4683bec1e12)

If you stand at the location drawn in the picture and use third-eye you can acess the stash of the room next door.

![image](https://github.com/echoroleplay/feedback/assets/138974765/3585d786-2752-4e62-849f-f392ae726557)

All that is left of my stash.

**Comment by C4LLZ** [comment]
I have made some changes. Thank you for a detailed bugreport!
