### ISSUE TITLE
Putting a tupperware container inside of itself.

### ISSUE THREAD

**Issue by jowebb7** [echoroleplay/feedback#314]
Description: You are able to open a tupperware container and place the item inside of itself and it disappears. I am unaware if this is also an issue with other containers. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Open Container
2. Place inside

**Expected Behavior:** Error

**Actual Behavior:** Disappears

**Comment by C4LLZ** [comment]
Should be fixed shortly!
