### ISSUE TITLE
Value of Life Enforcement

### ISSUE THREAD

**Issue by LiterallyLowd** [echoroleplay/feedback#319]
**Suggestion Description**
There is too many people flying mock Jesus through the roads. Slamming into things and not RPing anything out. I'd like to see staff enforce the value of life a bit more to match what the community's "offers" state 
"Quality Roleplay
Holding our roleplay quality to a high standard allows you to do things you always dreamed of, without having to worry about those who wish to ruin your fun. Whether it be participating in street races, illegal night life, attending community events, or otherwise - we strive to have quality interactions in all that we do."

**Reason**
I'm new to this community, joined almost 4 weeks from posting this, I joined because I was told this community takes RP to a new level and has fun but keeps things realistic. What I've seen thus far has not been to a new level or realistic. I'm seeing cars left and right flying mock Jesus through the streets. in an hour My delivery truck was T-Boned 3 times maybe 4 times where both cars stalled from them flying into it at mock Jesus speed but they turned their car back on and simply sped off. There's no value to their lives what so ever nor desire to RP. 

**Additional context**
I don't mean this to be like "oh this place sucks" but more simply as a new player my expectations from what the website says and applications and rules show VS what I've seen since I've gotten into the community.

**Comment by C4LLZ** [comment]
If you feel like people are providing LQRP. Please open a ticket.
