### ISSUE TITLE
Reimplement giving garage slots when purchasing a property

### ISSUE THREAD

**Issue by funkffn** [echoroleplay/feedback#322]
**Suggestion Description**
Beforehand, you'd buy a property and get 3 garage slots automatically. This makes sense. I buy a house in real life, It makes sense that I could park my car in my drive way or garage.

I am suggesting we either go back to 3 cars or at a minimum, 2 cars. So people who go in on a house together can park each of their cars there.

**Reason**

Why was it changed to now give us 0 garage slots and we have to make an extra 10k purchase PER slot. You spend 150k on a house and you still can't wake up there because you don't have a car there to drive around. If you want to have people with too much money spend more money, instead add an increasing fee past the 2nd or 3rd slot. 10k to upgrade from 2 to 3. And then 15k for 4, 20k for 5, etc etc.

At least this way when you purchase a house you can actually live there.

**Comment by C4LLZ** [comment]
https://discord.com/channels/561258884719968257/842997691591688212/1127220881693876294

**Comment by funkffn** [comment]
> https://discord.com/channels/561258884719968257/842997691591688212/1127220881693876294

Unsure if you mean that that discord link is the appropriate place to put this suggestion or feedback.

However the administrator has made it so no one can type in there.
