### ISSUE TITLE
Can not Desposit money into bank account (not even in a bank)

### ISSUE THREAD

**Issue by JoeyHenkerson** [echoroleplay/feedback#323]
**Description:** i am negative in my bank account and i can not deposite money into it not in a bank 3th eyeing it does not work

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. be in debt 
2. have anough money to pay it off
3. go to a bank and i can not interact with the employer 

**Expected Behavior:** i expect that i can 3th eye the cassier at the bank to deposit money

**Actual Behavior:** it does not net me interact with the bank emplyer

**Screenshot(s)/Video(s):**

**Comment by FlawwsX** [comment]
Can you provide a video of this? There's nothing 'debt' related with the target.

**Comment by JoeyHenkerson** [comment]
I did not make a video but i fixed itself after 2 days

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
