### ISSUE TITLE
repeating text from garbage runs

### ISSUE THREAD

**Issue by DistributedDenialOfService** [echoroleplay/feedback#324]
Description - while doing garbage runs, instead of the text clearing at the end of a run, it will repeat and continue to add more and more textr to your alt context menu. as an example, if you do several runs with friends, it will stack the prompt that appears to collect bags, until it becomes scrollable.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. join/start garbage run and collect bags
2. end run, start next run
3. third eye bin and watch the list of ''collect bag'' grow

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.
it should reset each run

**Actual Behavior:** Describe what actually happened instead.
it spams the heck out of your screen 

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.
unable to capture due to the keybind not working while pressing alt

**Comment by FlawwsX** [comment]
This was an issue @StuxxyOfficial identified, I think a fix should be pushed soon

**Comment by DistributedDenialOfService** [comment]
> This was an issue @StuxxyOfficial identified, I think a fix should be pushed soon

awesome, hopefully sooner than later, since it's reasonably annoying to see. there are a few other issues with teh garbage script but others have likely raised them already
