### ISSUE TITLE
Police Vehicle Radar won't open

### ISSUE THREAD

**Issue by FRNG1** [echoroleplay/feedback#326]
**Description:** When opening the police vehicle radar remote through the F1 Menu, the remote comes up, but the display will not. I can't hear any beeps from turning on or off any of the XMIT settings either.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Open the police vehicle radar via F1 menu
2. Hit "Toggle Display"

**Expected Behavior:** Vehicle radar display appears and can turn on the front and rear antenna.

**Actual Behavior:** Nothing happens.

**Screenshot(s)/Video(s):** [Don't judge me for using clipchamp.](https://clipchamp.com/watch/2oMCJ1flAfa)

**Comment by FlawwsX** [comment]
F8 console logs would have been really helpful.

**Comment by damightylamb** [comment]
I can't seem to replicate at all. If you happen to get it again, could you please share your F8 when reopening this issue? Thanks.
