### ISSUE TITLE
Boosting Que is a bit weird

### ISSUE THREAD

**Issue by GradualSquash** [echoroleplay/feedback#327]
Was sitting in the que for almost 2 hrs and didn't get anything, however someone else in our group was able to get the boost 5 minutes later and finish there boost.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get in que 
2. Expect boosts
3. Get no boosts :( 
4. Friend gets boosts

Should be getting boosts in a proper que system :(

People getting boosts before people who have been in it for longer

**Comment by FlawwsX** [comment]
Nothing is weird about it, there's just a limit on the number of boosts you can do per restart.

**Comment by SuspiciouslyStickySock** [comment]
Something i noticed was i joined the boosting queue around 9:30am i didn't get a boost for like 1h so I left the server, when I came back around 1 and joined the server i was instantly given a boost.

Is the queue skipping people who have left the server?

**Comment by GradualSquash** [comment]
Don't get me wrong, before the "big wave", I was able to get boosts like none stop, every 45min - 1hr I was getting one. But now it seams its a bit weird. IE I have sat in the boosting que for in total maybe 5 hrs from 2 storms and one did one boost, however a friend of mine was only in the que for an hour or 2 and managed to get 2 boosts already.
