### ISSUE TITLE
House robberies

### ISSUE THREAD

**Issue by davidbnp** [echoroleplay/feedback#330]
**Description:** Going to a house and i cant rob it, no door that says enter house and if i use lockpick at that exact house or any near by it wont say get closer to door
**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
Im not sure, it happens randomly, i go rob a house everything is fine, the next one its scuffed

**Expected Behavior:** Going to a house and being able to rob it
**Actual Behavior:** Going to the house and no door to lockpick
**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by davidxd33** [comment]
Not enough actionable information, please reopen with a video of this happening along with your F8 console log.
