### ISSUE TITLE
Cannot pick up skateboards even when there is inventory space for it

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#331]
**Description:** Cannot pick up skateboards even when there is inventory space for it

**Reproduction Steps:** 
1. put a skateboard down
2. have a decently filled inventory but not full
3.  try to pick it up 

**Expected Behavior:** you should be able to pick it up as you still have 10 lb of space as it only weighs 10lb

**Actual Behavior:** will not let you

**Screenshot(s)/Video(s):** 
Some Context: I found that when my inventory was over 190lb it wouldn't let me pick it up but when my inventory was below 190lb it would allow me to pick it up. seems that the script thinks the board is 60lb when its 10lb

https://medal.tv/games/gta-v/clips/1iNTl6YdPZPjS8/d1337Nr4a1Vw?invite=cr-MSxVcVUsMTc5NzI4NDkzLA

**Comment by davidxd33** [comment]
Thanks for reporting, the issue was found and fixed.
