### ISSUE TITLE
Bird Hunting Changes

### ISSUE THREAD

**Issue by Hanibex** [echoroleplay/feedback#335]
**Suggestion Description**
Allowing pistols to be used while bird hunting and also adjusting pay per bird. 

**Reason**
The birds are top gun pilots. Using a rifle is rather slow and typically ends up being a waste of ammo compared to the price of each bird at 24 dollars a piece. So as it currently stands, bird hunting is not worth the cost, time, and effort put into it. 

**Additional context**
Perhaps it's a skill issue, but I believe a pistol is more appropriate for birds anyway, rather than a bullet meant to take down a full sized buck or wild hog. It allows for faster aiming and a hair more precision.

**Comment by Kevbroseph** [comment]
Something like this.
https://www.gta5-mods.com/weapons/izh-58-animated

**Comment by Hanibex** [comment]
Well I'm no expert on actual bird hunting, was only thinking of what's available in the game currently. But yes, a low power shotgun would work.

**Comment by Kevbroseph** [comment]
The reason why a rifle or shotgun is never used is because it's borderline impossible to hit a bird for one.
For two, it's extremely dangerous to fire high velocity projectiles into the air.
Seeing as realistically you could kill someone from miles away.
Which is one of the reasons hunting birds on the ground through RP was approved.
A shotgun with target/bird shot has TINY pellets that are insignificant after a short distance.

**Comment by Kevbroseph** [comment]
Which is also why I have put in 2 suggestions on hunting.

**Comment by Hanibex** [comment]
I see your suggestion now, but I've noticed that the birds are never on the ground. Probably it not being their coded behavior.

**Comment by Kevbroseph** [comment]
> I see your suggestion now, but I've noticed that the birds are never on the ground. Probably it not being their coded behavior.

Find out IC about the birds.
There are people who know.

**Comment by damightylamb** [comment]
Bird hunting with a pistol seems crazy to me. There are some shotgun options available from ChiChis that could possibly be used.

**Comment by Kevbroseph** [comment]
There is one shotgun currently available from Chi Chi's.
It is the sawed off double barrel shotgun.
Issue is, it has next to nothing in range and spread is awful (which makes sense for what it is)
The other issue is that when killing any bird with is such as the ones that can be skinned on the ground within range, it provides "shit quality" skinning.
