### ISSUE TITLE
Gap in Fence at BB Round 2, Post 3rd shift storm

### ISSUE THREAD

**Issue by LordRusch** [echoroleplay/feedback#336]
**Description:** Please ** Fence had reverted after 3rd shift storm to having a gap

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Step one:  Looked at fence before storm and seen it was fixed
2. Step two: Came back to fence to show off how cool it was that the contractors fixed it and it was back to the gap.
3. ... Came here to let

**Expected Behavior:** Fence to be fixed, (Which it was)

**Actual Behavior:**  Fence reverted to pre-fix and has gaps for people to sneak through.

**Screenshot(s)/Video(s):**
2nd Shift prior to storm
![image](https://github.com/echoroleplay/feedback/assets/138604604/6643de85-0d8c-4a2b-b0ad-ac26e3dbf999)

3rd shift after storm
![image](https://github.com/echoroleplay/feedback/assets/138604604/1b81452b-adb0-43fa-b85a-0b0d5ad4b3fc)

**Comment by FlawwsX** [comment]
Was some merging issue, has been resolved now.
