### ISSUE TITLE
Option to conceal or expose weapons with a duffle bag.

### ISSUE THREAD

**Issue by Kevbroseph** [echoroleplay/feedback#339]
**Suggestion Description**
Add an option to determine whether or not the duffle bag conceals a holstered weapon.

**Reason**
Adds more immersion and would make more sense in certain things/themes such as hunting.

**Additional context**
I had to hide the bag, draw the weapon, holster the weapon, and then unhide the bag in order to achieve this.
It stops showing the firearm once I open my inventory or draw and holster the firearm again.

![image](https://github.com/echoroleplay/feedback/assets/136265699/1a822c08-abab-4e63-aa1b-7732c30fdea8)

**Comment by damightylamb** [comment]
I like the idea. Its a long boi anyways. Ill make a push.
