### ISSUE TITLE
Exporting bank transactions from Fleeca locations

### ISSUE THREAD

**Issue by Dano0942** [echoroleplay/feedback#341]
**Suggestion Description**
Give the ability to export a .CSV (or similar file type) of all bank transactions directly from Fleeca teller.

**Reason**
With the recent inclusion of employee paycheques to the transaction logs, Business bank accounts now have a complete history of transactions. This transaction history is now useable and I would love to be able to export this and use it to complete the business books. This would also give the ability to track the "on duty time" of staff.

**Comment by FlawwsX** [comment]
This would never happen.
