### ISSUE TITLE
C Class providing no additional SVC as reward

### ISSUE THREAD

**Issue by Freakerdoodle** [echoroleplay/feedback#348]
**Description:** Upon completing a C class boost, no additional SVC is rewarded and instead the initial cost is split between the driver/hacker. (not sure if this is intended but it would provide a bottleneck for D class in the long run as people begin reaching the higher tiers)

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Obtain C class boost, pay the required SVC
2. Complete the boost
3. Drop the car off at the specified location

**Expected Behavior:** Original payment for boost gets repaid to the person who paid it, then extra is split over the driver/hacker as a 'reward'

**Actual Behavior:** Exact same amount of SVC is returned, but split between the driver/hacker, no additional is given as a reward

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1j2J8ssOmL7Ew_/d1337uBbTeKz?invite=cr-MSxFMDMsMTgyMDgzNzE0LA

**Comment by davidxd33** [comment]
Looks like this was resolved this morning, let us know if this is still happening.
