### ISSUE TITLE
Holsters Taking Long Time to Unholster

### ISSUE THREAD

**Issue by MamaPrince** [echoroleplay/feedback#35]
**Description:** Holsters since the spring update take approximately 3-4 seconds to unholster once you go to draw your firearm

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Wear a holster (i.e the belt one for pd)
2. Draw your firearm and time it
3. Might have to do it the 2nd time, first time usually unholsters immediately 

**Expected Behavior:** Draw immediately and not take 3-4 seconds. 

**Actual Behavior:** Takes approximately 3-4 seconds to draw your firearm

**Screenshot(s)/Video(s):** Not sure if this is by design or if affects civs as well but cops have stopped wearing holsters to bypass the 3-4 second delay to allow them to unholster immediately

**Comment by iZolox** [comment]
@spiegeljoshua Could you provide a clip and maybe a list of holsters this bug applies to?

**Comment by MamaPrince** [comment]
> 

Yeah I can get you those tomorrow

**Comment by damightylamb** [comment]
Pushed a fix for restart
