### ISSUE TITLE
Prison Collisions

### ISSUE THREAD

**Issue by Tristana4815** [echoroleplay/feedback#352]
**Description:** Collision bug at new Prison interior. Located in the sewing room, against the window. Floor is missing a strip of collision, making you fall through the floor into the room below. 

**Reproduction Steps:**
1. Enter BB and find Sewing Room (Above mechanic working room)
2. Walk all the way against the window (Window not pointing towards the yard)
3. Fall through floor, into room below

**Expected Behavior:** I would expect that you can walk on the floor without falling through.

**Actual Behavior:** Collision is missing, you fall through the floor.

**Screenshot(s)/Video(s):**

https://github.com/echoroleplay/feedback/assets/139397997/48050d24-61df-48e4-a558-745b6d9c22c4

**Comment by Stickerzz** [comment]
Fixed!
