### ISSUE TITLE
Being able to view cameras, while down.

### ISSUE THREAD

**Issue by brytime** [echoroleplay/feedback#360]
**Description:** The bug I am reporting, is with the new camera script that was added (sick btw), you can view them while you're down.

**Reproduction Steps:**
1. Go down (RIP bozo)
2. Do /cameras
3. You should be able to view the cameras, while down.

**Expected Behavior:** I believe there should be some sort of down check if you are down when trying to view cameras, similar to checking your inventory, going on your phone ect, while down.
**Actual Behavior:** You can view the cameras while down.

**Comment by Kevbroseph** [comment]
The reason why I'm OK with using them while downed is to record legitimate angled camera footage of evidence on what's happening. If they are calling out while down. Then report that shit.
