### ISSUE TITLE
Instead of boost cars exploding they just become inoperable 

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#364]
**Suggestion Description**
Instead of the boost exploding make it that the car becomes disabled, locked and unable to be repaired. Either that or another solution besides exploding.

**Reason**
So lately myself and other officers have noticed that boost cars tend to go kaboom when a boost goes for too long. Purely from police perspective it is annoying to deal with as the car could explode at anytime on our end and can be like playing roulette when you want to process it. In addition to this, I also miss boosts lasting more than 30 minutes as long chases can be super fun on the PD side.

I also want to add that from an RP perspective it doesn't make much sense for the PD to just let these mobile bombs just drive around willy nilly due to public safety concerns lmao.

**Additional context**
none

**Comment by damightylamb** [comment]
Made an adjustment.
