### ISSUE TITLE
No Collisions for the backside of the Beeker's Office building

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#368]
**Description:** No Collisions for the backside of the Beeker's Office building

**Reproduction Steps:** 
1. walk upto the wall on the backside of the beeker's office area

**Expected Behavior:** wall is wall and has collisions

**Actual Behavior:** you can walk into the wall and climb stuff to get into the building

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1jlUWQiWfhzjdu/d1337zGo1tFa?invite=cr-MSx2d04sMTc5NzI4NDkzLA

**Comment by Stickerzz** [comment]
Fixed.
