### ISSUE TITLE
loophole that allows players to use items and continue to shoot at the same time

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#370]
**Description:** You can apply armour and use meds and continue to shoot without cancelling its use

**Reproduction Steps:** 
1. Have your gun out
2. Apply armor or an ifak (this causes your character to put the gun away)
3. Draw your gun back out and continue to shoot

**Expected Behavior:** It should cancel the use of the item as your character doesn't have 4 arms

**Actual Behavior:** you can use said item and still continue to shoot

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1jpIj4vGsNMMo1/d1337CZn5WOY?invite=cr-MSxYUVAsMTc5NzI4NDkzLA

**Comment by YeahF10** [comment]
This has been in the server for awhile and I don't believe its a bug. When you shoot your weapon it will cancel any action you are doing.

**Comment by RADSTAR55** [comment]
oh I wasnt aware it would cancel upon shooting

**Comment by MamaPrince** [comment]
Idk about that one YeahF10. Pretty sure when PD does hot drops in helicopters we prearmor upon dropping. Essentially putting on armor and still being able to shoot

**Comment by FlawwsX** [comment]
Unable to reproduce, seems to cancel upon shooting.
