### ISSUE TITLE
Big Pawn Not Working As Intended  (Not receiving any money while trading) 

### ISSUE THREAD

**Issue by Moupra** [echoroleplay/feedback#373]
Starting Big Pawn with over 25 big pawn items in my character's inventory and when I trade with the NPC, none of the items gets removed from my inventory nor do I get any money from it just some Xanx and that's it. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Have 25 or more Big Pawn items in your inventory
2. Start big pawn run
3. trade with NPCs

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.
I expect for the items to be removed and receive money 

**Actual Behavior:** Describe what actually happened instead.
The items were not removed and I didn't get any money
**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

Link to video: (Couldn't upload file too big) 
https://medal.tv/games/gta-v/clips/1jq02rqRBCfJub/d133732KTBCf?invite=cr-MSxLSnUsMTU3MDcxNTk1LA

**Comment by StuxxyOfficial** [comment]
Doesn't look like big pawn to me. perhaps you have the wrong information ic.

**Comment by damightylamb** [comment]
That is not big pawn, correct.
