### ISSUE TITLE
Cannot enter trunk of vehicles.

### ISSUE THREAD

**Issue by Innovation-0** [echoroleplay/feedback#38]
Issue Description: Cannot enter trunk of any vehicle using F1 wheel. 

Steps to reproduce the issue:
1. Walk up to back of trunk of trunk.
2. Open F1 wheel to enter trunk. 
3. Select Enter Trunk.
4. Does not enter trunk.

What's the expected result? Able to enter the trunk. 
What's the actual result? After selecting the option, nothing happens. Doesnt enter trunk.

Additional details / screenshot(s): 

https://cdn.discordapp.com/attachments/1112297776483663962/1112401504314335262/vlc-record-2023-05-28-10h25m28s-Desktop_2023.05.28_-_10.23.59.18.DVR.mp4-.mp4

**Comment by FlawwsX** [comment]
Resolved
