### ISSUE TITLE
House robbery link up

### ISSUE THREAD

**Issue by davidbnp** [echoroleplay/feedback#384]
**Description:** Please **replace me** House link up scuff

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Do 1 house
2. Start a second house robbery
3. It says your group members are on cooldown even though you are alone and even waited for 30 mins

**Expected Behavior:** Being able to do another house after the normal cooldown time
**Actual Behavior:** Says my members are on cooldown and i cant do a house

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by StuxxyOfficial** [comment]
this is not a bug, cooldown was increased
