### ISSUE TITLE
Leave engine running upon exiting vehicle

### ISSUE THREAD

**Issue by Xoogle5M** [echoroleplay/feedback#391]
**Suggestion Description**
Add the functionality to leave the engine running when you long press "F" to get out of your car. Just pressing "F" once would turn off the engine as you get out, as usual.

**Reason**
It gets annoying having to hotwire cars over and over again when you just step out of them for a few seconds to talk to an NPC or whatever. It's also not realistic having to do that, being able to leave the engine running would be a nice "fix" to this.

**Additional context**
N/A

**Comment by damightylamb** [comment]
This is already a feature for cars you have keys with, but not with hotwiring cars. There is a trade off with hotwiring vs lockpicking/owning.

**Comment by Xoogle5M** [comment]
> This is already a feature for cars you have keys with, but not with hotwiring cars. There is a trade off with hotwiring vs lockpicking/owning.

Ah, fair enough. Didn't know there was a difference like that with hotwiring/lockpicking. Fine to close then :)
