### ISSUE TITLE
Country and Gang Weapon Animation(s) are still broken.

### ISSUE THREAD

**Issue by Arcfull** [echoroleplay/feedback#393]
**Description:** When using the Gang or Country weapon animations, you will always fire at least 2 bullets instead of 1 upon a single click.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Equip Gang/Country Weapon Animation (with a pistol)
2. Click once.
3. Shoot twice.

**Expected Behavior:** Shoot once.

**Actual Behavior:** Shoots twice.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

Here's a video link to visualize the issue: https://medal.tv/games/gta-v/clips/1jEeZq_apr_Hf-/d1337OmGSSHb?invite=cr-MSx6TU8sNDgxNjY3NzUs

At the beginning of the video, I am using the Country weapon animation, it shoots twice, and then I swap to Gang in the second half, where it shoots twice. For the final portion, I do the same exact action with my mouse, but on the Default animation, and it shoots once.

**Comment by FlawwsX** [comment]
Not really a bug, just GTA behaviour.
