### ISSUE TITLE
Xanax doesn't pay any cash

### ISSUE THREAD

**Issue by QuiggUK** [echoroleplay/feedback#394]
**Description:** Xanax doesn't pay any cash

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Start the Xanax run.
2. Go to drop off, trade notes and you get a prompt to say you have receieved X amount of cash.
3. Check cash, nothing given.

**Expected Behavior:** Cash to be given

**Actual Behavior:** No Cash is given

**Screenshot(s)/Video(s):** [If possible, add screenshots or videos to help explain your problem.](https://youtu.be/8KBmbWmrg8Y)

**Comment by FlawwsX** [comment]
Fixed.
