### ISSUE TITLE
Character Selection Screen is Old One

### ISSUE THREAD

**Issue by MamaPrince** [echoroleplay/feedback#40]
**Description:** Sometimes you get the old character selection screen and not the new one with the spring update

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Launch FiveM
2. Be met with old selection screen

**Expected Behavior:** Have the new character selection screen

**Actual Behavior:** Sometimes be met with the old one

**Screenshot(s)/Video(s):** https://i.imgur.com/6rCpT0H.jpeg

**Comment by SuspiciouslyStickySock** [comment]
Pretty sure this is not a bug, i remember seeing this posted in discord and it is meant to change between them

**Comment by iZolox** [comment]
Awaiting to see if this is intentional.

**Comment by FlawwsX** [comment]
This is intentional.
