### ISSUE TITLE
Police Vehicle Radar Not Working (reopening)

### ISSUE THREAD

**Issue by FRNG1** [echoroleplay/feedback#408]
**Description:** When opening the police vehicle radar remote through the F1 Menu, the remote comes up, but the display will not. I can't hear any beeps from turning on or off any of the XMIT settings either.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug.

Open the police vehicle radar via F1 menu
Hit "Toggle Display"
Expected Behavior: Vehicle radar display appears and can turn on the front and rear antenna.

**Actual Behavior:** Nothing happens.

**Screenshot(s)/Video(s):** https://clipchamp.com/watch/YVPA5A2PnU6

**Comment by FlawwsX** [comment]
@FRNG1

**Comment by FRNG1** [comment]
Yes, sorry I have an 21:9 and a 16:9. I think I may have swapped to the 16:9 once a while ago. That’s possibly when the issue started and I just didn’t notice since I took some time off GTA RP

**Comment by FRNG1** [comment]
Update: I searched up the github of the radar and found a reset command "/reset_radar_data", which prompted me to restart my game and when I loaded back in it was fixed. Issue is now fixed and can be closed.
