### ISSUE TITLE
Linkup app stuck

### ISSUE THREAD

**Issue by TeammateBlamer** [echoroleplay/feedback#409]
**Description:** The queue hasnt moved for multiple hours, Sat at 3/3 in bank queue for an hour and a half and didnt move, gave up and got in house queue. Barely moved in 3 hours

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get in queue on linkup for bank, houses etc 
2. wait
3. nothing

**Expected Behavior:** queue should move and jobs should be popping 

**Actual Behavior:** Sit in queue for multiple hours and only move when someone ahead of you drops out 
**Screenshot(s)/Video(s):**https://i.imgur.com/btww3TY.png

**Comment by TwoTaDile** [comment]
I'm having the same issues, with all of the activities mentioned above.

**Comment by StuxxyOfficial** [comment]
We're aware of an issue that has caused the queue to freeze. I am working on it as we speak.

**Comment by FlawwsX** [comment]
This should be fixed now.
