### ISSUE TITLE
Replace me with a brief and clear title describing the bug

### ISSUE THREAD

**Issue by Trixxx214** [echoroleplay/feedback#412]
Internals Bug 
So this has happened to a couple of people with me included is when you start doing internals and use the item it wont show an option no matter how many types you keep trying until you relog , i did everything i deleted cache reinstalled fivem and still have the same issue , another thing is when you use a wire it doesn't show a progress bar and when the item gets removed, the electronics level on the internals don't go up , My suggestion to fix this issue and make life a bit easier for mechanics is to add a command or a third eye option called " internals view " where you can see all the icons for the internals like when mecca uses a blowtorches they see all parts , that  will be a huge QOL improvement for mechanics . 

this happened to me yesterday and i had to relog about 4-5 times to do internals on two cars . 

**Reproduction Steps:**

1.Use any part to fix internals after a couple you wont be able to do anymore 
2. Use a wire to fix electronics 

**Expected Behavior:** 
An icon of the part will show for you to repair when you use the part
**Actual Behavior:** 
nothing show up until you relog then you can start repairing

**Comment by PaulRobson2002** [comment]
Are there any F8 console errors that appear when this occurs?

**Comment by Trixxx214** [comment]
no F8 erros
