### ISSUE TITLE
Cars are gaining/losing liveries in public garages

### ISSUE THREAD

**Issue by feedmeee-x** [echoroleplay/feedback#42]
**Description:** My Issi Sport gained a livery while parked at vespucci public garage. I went to AE to have it removed and they said many people are having issues of liveries/visual customizations not sticking or appearing out of nowhere.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
Unsure about steps to test here, I was advised not to modify livery as it might not persist and I'd be wasting money. If someone could advise what theyd like me to test I'd be happy to, although this seems to be a common/known issue

**Expected Behavior:** Car to keep cosmetics as configured

**Actual Behavior:** Car gained livery not applied

**Screenshot(s)/Video(s):** 
![image](https://github.com/echoroleplay/feedback/assets/134959051/03589406-f596-47d5-b1b4-4dfe2da89098)

**Comment by SergeantGun** [comment]
Also does it in personal garages.

**Comment by FlawwsX** [comment]
After applying your livery, is it still an issue? It seems to work fine for me on test.

**Comment by feedmeee-x** [comment]
was something changed then? I can retest it if so. because that livery appeared today by itself, I had nothing applied

**Comment by davidxd33** [comment]
> was something changed then? I can retest it if so. because that livery appeared today by itself, I had nothing applied

Yes, reapply the livery and park the vehicle.
