### ISSUE TITLE
Local cars disappearing when pulling phone out while getting inside

### ISSUE THREAD

**Issue by NotTokkii** [echoroleplay/feedback#420]
**Description:** When getting in a local car and pulling out your phone at the same time the local car will dissappear

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Attempt to get in local car
2. Pull out phone while getting in the car
3. Car disappears 

**Expected Behavior:** to get in the car and pull your phone out
**Actual Behavior:** car disappears then you pull your phone out

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1k10stYq4R4b0G

**Comment by Xoogle5M** [comment]
+1 just happened here too.
