### ISSUE TITLE
Voice indicator does not change color when talking.

### ISSUE THREAD

**Issue by Marascon** [echoroleplay/feedback#432]
When talking in the city, the voice range indicator does normally change color indicating you are talking, but after reset they stay solid white

**Reproduction Steps:** 
1. Spawn in city
2. try to talk in the city (default key `N`)

**Expected Behavior:** See voice indicator change to blue while talking, or yellow when talking over radio

**Actual Behavior:** Voice indicator stays white all the time, giving the impression voice is not working

**Screenshot(s)/Video(s):** N/A

**Comment by FlawwsX** [comment]
Resolved
