### ISSUE TITLE
Tier 4 Hack Issue

### ISSUE THREAD

**Issue by Splakes** [echoroleplay/feedback#437]
**Description:** This is the second time I have had the issue. I am unable to do the Tier 4 house hack. It just creates a phone & sometimes a USB, drops it, and I do not get the opportunity to do the hack. The houses are my own and I have a hacking device in my main inventory.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get tier4 house.
2. Try to hack it w/ hacking device.
3. Chance that you cannot enter the hacking screen.

**Expected Behavior:** Tier 4 hack pops up.

**Actual Behavior:** Phone and USB created and dropped, no hack screen pops up.

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1kpfYD9gPwFaUk/d1337vGofmYE?invite=cr-MSxKNFksMTYzMzc3OTA1LA

**Comment by Morphiushell** [comment]
When you enter the house wait 30 seconds then attmept the hack it will work

**Comment by Splakes** [comment]
I had already waited a minute or two at that point and been in and out of the house as well.

**Comment by damightylamb** [comment]
I pushed a potential fix for when flawws pulls next. Reopen if it happens again.
