### ISSUE TITLE
Cannot Claim Malicious USB

### ISSUE THREAD

**Issue by TwoTaDile** [echoroleplay/feedback#438]
Go to life invader in order to craft a malicious USB, and after using the computer to inform you where to go within the time frame to meet the individual, he is not present on any spawn on the map I've been directed too (tried five times). 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Use USB at lifeinvader 
2. Follow Directions given on GPS
3. See nothing at the location. 

**Expected Behavior:** Meet at the location and see the NPC to craft usb. 

**Actual Behavior:** NPC doesn't spawn and is not present at the location. 
 
**Screenshot(s)/Video(s):**  
https://cdn.discordapp.com/attachments/1127117698594263091/1131450652074192966/image.png

https://cdn.discordapp.com/attachments/1127117698594263091/1131452062329212988/image.png

**Comment by damightylamb** [comment]
Not a bug. I made it intentionally snubb you 😄. Can happen at any time. I think you're getting unlucky. I will look at the code to check its not a bug, but if it keeps happening, please reopen it.
