### ISSUE TITLE
EchoRP Glizzy Job Bug

### ISSUE THREAD

**Issue by JaybullOG** [echoroleplay/feedback#449]
The Glizzy Hotdog job isn't working as intended. You can start the job normally, all of that works fine but as soon as you begin selling & you get a customer to approach you, no further interaction happens. You can cancel the job fine, restart & try again fine. It just seems to stop you from actually doing the selling section of the job.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Step one: Start the job, head to the Glizzy stand
2. Step two: Third Eye over the stand & select "Start selling" 
3. Step three: NPC customers approach & then no further interaction occurs.

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.
Usually when a customer approaches you, an interaction begins with a countdown bar & then a second interactive bar starts where you press "E" at a specific time.

**Actual Behavior:** Describe what actually happened instead.
Instead, as soon as a customer spawns & approaches you, nothing further happens. They just stand there & more & more NPCs can spawn & just clump up. If you cancel the job (which you can just fine) the NPCs will eventually walk away & then de-spawn.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

![EchoGlizzyF8](https://github.com/echoroleplay/feedback/assets/112963693/c21b8fc0-49ef-4667-a327-bb4fb0f592b3)

https://github.com/echoroleplay/feedback/assets/112963693/13724eda-c902-400a-abac-ce5717d3ac70

**Comment by karichandesu** [comment]
https://cdn.discordapp.com/attachments/1002173485629575209/1132300152397365349/image.png I kept getting this. Not sure if it's been fixed yet.

**Comment by taliph** [comment]
getting the same as above after restart

**Comment by damightylamb** [comment]
Should be resolved
