### ISSUE TITLE
Kicked from Linkup App

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#45]
**Description:** When you are queued up for houses you can be randomly kicked from queue for no reason

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Be in queue for houses
2. Get kicked randomly
3. Cry

**Expected Behavior:** Be in queue until your job pops

**Actual Behavior:** Get kicked without any notification

**Comment by FlawwsX** [comment]
Unfortunately, without any information, there's nothing we can do here. There should be at least some sort of feedback on the phone or notification if you were removed from the linkup app.

If you are unable to provide any information within 48 hours, I'll close this one out.

**Comment by SuspiciouslyStickySock** [comment]
Feel free to close, sadly i am unable to provide any feedback. There is nothing that notifies of being removed from the queue, we go to check the queue and notice that we have been removed
