### ISSUE TITLE
Wipe criminal record if assets are wiped

### ISSUE THREAD

**Issue by Loaqki** [echoroleplay/feedback#451]
### **Suggestion Description**
Wipe criminal record if assets are wiped.

### **Reason**
If a person gets into criminal activity, he does it for money, if the money disappear, CR should follow the money

### **Additional context**
The person who worked illegally to get the money he had pre-wipe is going to lose every money/assests he got caught for because of a wipe, but he won't lose what follow the money, the criminal record. 

The situation seems unfair since a player starts back from 0 and has to work again all he already did, but with a handicap ; he's still a felon because of pre-wipe. 

It means he can't access certain legal job, he doesn't get the paycheck that is supposed to help him start like he should when he is starting at 0$, and he is a recidivist, which basically don't help him at all (For exemple, when you get caught for the first time, they are chill on you, and you don't suffer the same as a guy who's gone to jail 20 times).

In RP, if the Tsunami swallowed all the money of National banks because it flooded 1 city, I don't see why it wouldn't have swallowed the CR of the Police Departement of just that city.

### **Exemple** 

 **Let's say your objective is $100k and you start at $0:**

**Paycheck** 
By the time you work and get into illegal etc... you get around **$10k if you're not felon. If you are felon, you'll get 1k** for the same number of paychecks.

**Legal job** 
If you don't get caught or get caught for small charges that don't make you a felon, you can have a legal job as a side hustle + you can still work after getting caught if your employer doesn't see that you got caught after engaging you. **$20k from legal if you work 50/50 with good crim/civilian balance.**
(Note : Mechanic don't care about CR, but half the server isn't going to be mechanics).

**If you get caught** 
If it's the first time, they might reduce the fine and the jailtime. **- $Xk and -Time not used for work**, if you are recidivist

**Conclusion** 
You're drawn back around $30-40k while you try to go to a $100k from $0 just because of the CR made of a money you don't have anymore.

PS : I don't know if it is the right place to post this, if not feel free to delete it, excuse me about this
PPS : This shouldn't be taken as a complaint, my apologies if it's misunderstood as such, just a thought process that I think a lot of people will agree with

**Comment by damightylamb** [comment]
This doesn't make sense. How does your assets reflect your criminal record?

**Comment by Loaqki** [comment]
> This doesn't make sense. How does your assets reflect your criminal record?

You don't usually (or rarely) do crim for nothing. Most of your charge for robbery / heist / boosting related / ... are mostly related to some kind of income. If your assests are wiped anyway, a certain % of it is through crime if you do crime so there is a correlation there

**Comment by damightylamb** [comment]
An economy wipe isn't a fresh start. It's to reset the economy. Wiping records would be for a full wipe, not the economy wipe.

**Comment by Loaqki** [comment]
> An economy wipe isn't a fresh start. It's to reset the economy. Wiping records would be for a full wipe, not the economy wipe.

Oh totally, we agree on that, it was just a thought about the fact some people will restart with a handicap, for something they did pre assets-wipe, that they don't have anymore

**Comment by damightylamb** [comment]
Its not like we stopped crime and forcing people to do civilian things. Crime is very much still happening and you can still make decent money doing it.

**Comment by Loaqki** [comment]
> Its not like we stopped crime and forcing people to do civilian things. Crime is very much still happening and you can still make decent money doing it.

Totally, but what I was trying to say is that it will take more time to get financially comfortable back for a person that was not clean before. 

I don't really know how to explain my thought because of the language barrier, the word unfair seems to rough but I can't think of a softer word. 

My idea is that, if everyone is back at no CR, with the same character, they'll most likely do what they were doing before (Previous criminal will do criminal things again, previous legal people will do legal things). And because of all the point said in the exemple above, Crims will get more difficulty to get back to what they had before, not only because they don't have acces to all they have now (Tools / laptop /...) but also because they are not clean, while on the other side, a Burger Shot employee will have the same wage, same job, ... Just his money will be gone.

**Comment by damightylamb** [comment]
`Burger Shot employee will have the same wage, same job` - not true. Businesses were effected so pays have been adjusted. There is more that you just don't see.

**Comment by Loaqki** [comment]
> `Burger Shot employee will have the same wage, same job` - not true. Businesses were effected so pays have been adjusted. There is more that you just don't see.

Forget about it, I don't think I'm able to understand the whole server economy and that's what's confusing me (^_^')

It was just a thought process from me in the beginning but it evolved in something else, and I don't want to waste your time by explainning to me the whole economy.

Thanks for taking the time to address my confusion, have a great evening 😃

**Comment by damightylamb** [comment]
No problem. Also, there is a new feedback website we are utilizing. Please use that for future suggestions/bug reports https://feedback.echorp.net/
