### ISSUE TITLE
Replace me with a brief and clear title describing the bug

### ISSUE THREAD

**Issue by MrE1ectric** [echoroleplay/feedback#455]
**Description:** While smoking joints and eating Vicodin, Xanax you no longer get armor and health back

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Smoke or eat a pill
2. Wonder why your not gaining health
3. File a bug report

**Expected Behavior:** gain health and armor 

**Actual Behavior:** Nothing happens at all

**Comment by C4LLZ** [comment]
Do /logout, Change clothes or anything.
