### ISSUE TITLE
Boosting

### ISSUE THREAD

**Issue by xxmustardxx** [echoroleplay/feedback#457]
**Suggestion Description**
Make it where to get a boost have to have the piece (for meta reasons) on you to keep you in que , what I mean is no more 1 person have one and drop it to 6-7 people to que, making it to easy and no fair to the people using their svc every week to get a new one, not to mention the que was over 150 last night that is insane i bet not even 1/3 had their own devices.

**Reason**
Not only for the boosting que, but should not be able to share one usb between tons of people and have them all que with the same device. I understand after a certain point have to take it with it you to do the job, but right now people that dont even have devices are all sharing theirs and farming a certain class without even having their own device. It is really not hard to get own device personally made at least 5.

**Additional context**
I did not screen shot the que last night but 150-160+ people in boosting que is insane.

**Comment by damightylamb** [comment]
Do you think you can move this suggestion to the new feedback website? We aren't using github anymore. 

https://feedback.echorp.net

**Comment by xxmustardxx** [comment]
> Do you think you can move this suggestion to the new feedback website? We aren't using github anymore.
> 
> https://feedback.echorp.net

yea my bad been a awhile since i looked at or did any of this
