### ISSUE TITLE
No Animal Emotes in Emotes menu for new Subscription Animal Ped

### ISSUE THREAD

**Issue by Vtek79** [echoroleplay/feedback#458]
Theres no Animal Emotes Section in the F3 Menu for my Subscription Animal Ped

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Open F3 menu
2. Look For "Animal Emotes" Section

**Expected Behavior:** There to be a Section for Animal Emotes on my new Poodle Ped

**Actual Behavior:** Its not there,  I have a PD K9 and its there for than but not on my new animal I got with the new Subscriptions 

First Screen shot is what I have and the Second is what it should be!! 
https://cdn.discordapp.com/attachments/1134304855113084969/1134649239763435570/image.png
https://cdn.discordapp.com/attachments/928585138651168790/1134571187956109403/image.png

**Comment by FlawwsX** [comment]
Please use https://feedback.echorp.net
