### ISSUE TITLE
LSRS Asset Tax Not Working

### ISSUE THREAD

**Issue by Morphiushell** [echoroleplay/feedback#459]
I have clicked Pay multiple times for my car and it has taken the cash but the option to pay is still there.

1. Open LSRS App
2. Find asses requiring to be paid
3. Click Pay Tax

**Expected Behavior:** Tax is paid 

**Actual Behavior:** Tax is not paid and still show that it needs paid

**Screenshot(s)/Video(s):** https://i.imgur.com/mpHXNeh.png

**Comment by FlawwsX** [comment]
Please use https://feedback.echorp.net
