### ISSUE TITLE
Employment app not updating employee salaries

### ISSUE THREAD

**Issue by SassiBubbles** [echoroleplay/feedback#460]
Employment app doesn't update the salary amounts although it updates the actual payout to the employee. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Adjust the salary of an employee in the app
2. Close out the app
3. Reopen the app and it does not show the change.

**Expected Behavior:** It's expected for the app to visually indicate the change in adjusted pay. 

**Actual Behavior:** The app continues to show the original pay even after the pay adjustment.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by FlawwsX** [comment]
Please use https://feedback.echorp.net
