### ISSUE TITLE
UwU Cafe drink machine not working

### ISSUE THREAD

**Issue by iamtacogod** [echoroleplay/feedback#47]
**Description:** Whenever you attempt to go to the drink machine and third eye it, it does absolutely nothing.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Go behind counter of UwU Cafe
2. Attempt to grab drinks from the machine
3. Not able to grab drinks from machine.

**Expected Behavior:** To be able to grab the drinks from the machine.

**Actual Behavior:** Not being able to grab the drinks from the machine at all.

**Screenshot(s)/Video(s):** 
https://i.imgur.com/mHjUVhH.jpeg

**Comment by Sassyopath** [comment]
C4LLZ, I know you're helping with biz stuff, but I think Demigod has been working on the target zone distance fixes- if one of you could look into this 💖

**Comment by C4LLZ** [comment]
I thought we were removing UwU?

**Comment by Sassyopath** [comment]
Low priority issue due to current circumstances. ✨

**Comment by Sassyopath** [comment]
Low priority issue due to current circumstances. ✨

**Comment by davidxd33** [comment]
> Low priority issue due to current circumstances. ✨
Nonsense this was my highest priority has been fixed for the next restart.
