### ISSUE TITLE
Crouch whilst aiming

### ISSUE THREAD

**Issue by Morphiushell** [echoroleplay/feedback#52]
I am unsure if this is intended however you can no longer pull your gun out and aim whilst crouching.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Pull out gun
2. Crouch
3. Unable to aim 

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.
Previously you were still able to aim and fire your gun when crouched

**Actual Behavior:** Describe what actually happened instead.
Can’t aim whilst crouched

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by FlawwsX** [comment]
Seems intentional.
