### ISSUE TITLE
(DOC) Discord clock

### ISSUE THREAD

**Issue by Moonhera** [echoroleplay/feedback#54]
**Description:** We recently got our clock back for DOC, so that we can track activity but also give the PD recruits the ability to check their hours and keep an eye on it. We have found that server restarts, head crashes and quitting out of the server will not send you 10-07 and not count your hours until you next do a manual clock out (through app, mdt and command [/toggleduty]), displaying inaccurate hours done. I understand if this cannot be fixed and we will find ways to make it work (we love our clock! Thank you so much for adding it)

**Reproduction Steps:** 
1. Clock on duty 
2. Work for a small while
3. Quit out of the server without clocking off duty
4. Go back on the server
5. Work for a small while
6. Clock on and off duty. 

**Expected Behavior:** For the clock to register you 10-07 and then register you 10-08 again. To clock actual hours done. 

**Actual Behavior:** Will register you as not working for several hours. 

**Screenshot(s)/Video(s):**

**Comment by FlawwsX** [comment]
Bumped to Lamb in DMs.

**Comment by damightylamb** [comment]
Pushed fix for restart.
