### ISSUE TITLE
Custom Items missing images

### ISSUE THREAD

**Issue by BillBloot** [echoroleplay/feedback#55]
**Description:** There are a few custom items that I've brought into the server, as well as, items from other people missing the images.  Names and descriptions are still present though.  

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Opened storage bin
2. viewed item.  It takes a spot but is not visible

**Expected Behavior:** Image to match the description

**Actual Behavior:** blank

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 
https://i.imgur.com/m3tRkl7.png
https://i.imgur.com/YOF0UJb.png
https://i.imgur.com/2xSwshn.png

**Comment by FlawwsX** [comment]
Bumped Callz in DMs.

**Comment by C4LLZ** [comment]
Should be resolved next restart
