### ISSUE TITLE
House robbing hack issue

### ISSUE THREAD

**Issue by XxThaHitmanxX** [echoroleplay/feedback#56]
When robbing a house if you do the hack and are too close to the door (example the apartment) you teleport in and out of the apartment and are unable to actually complete it because it does not allow you to use the E button.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Start a house robbery (at the apartment)
2. Start the hack and be within the range of the door.

**Expected Behavior:** Complete the hack if skilled enough

**Actual Behavior:** You go in and out of the apartment unable to complete the hack.

**Screenshot(s)/Video(s):** None at the moment but can get one if it is needed.

**Comment by Demigod916** [comment]
Same as issue #46

**Comment by XxThaHitmanxX** [comment]
duplicate, I did not look hard enough.
