### ISSUE TITLE
Drug run - car not spawning

### ISSUE THREAD

**Issue by ImUnreliable** [echoroleplay/feedback#58]
after packaging the drugs you get a location of the car, from this we unpacked the drugs and went to the location given to find a car not there

1. Start a drug run
2. Wipe locals at cayo
3. Package Drugs
4. Get pinged to drug car location
5. Go to spot to find nothing.

A car to be at the location to be ready to be packaged 

No car spawned

https://medal.tv/games/gta-v/clips/1bWvswfhCyERIj/d1337FAiJl0p?invite=cr-MSxtcGMsMTExNzg1NTQzLA

**Comment by FlawwsX** [comment]
@damightylamb Just use server-side vehicle spawning with state bags.

**Comment by damightylamb** [comment]
@FlawwsX that vehicle us server sided

**Comment by FlawwsX** [comment]
@ImUnreliable Although that commit marked this as resolved, I'm not 100% sure if it will be the fix for this. Feel free to re-open this if it happens again, thank you.
