### ISSUE TITLE
Accepting house robbery in warehouse will not give you the location and you get stuck in queue for the rest of tsunami.

### ISSUE THREAD

**Issue by DayOneNate** [echoroleplay/feedback#59]
If you accept a house robbery in a warehouse it does not give you the location of the house robbery and then you are stuck on "you're already doing a job" for the rest of the storm and can not cancel the job.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Queue house robbery
2. Get house job
3. Accept job in warehouse
4. Don't get house location
5. Stuck in queue for rest of storm.

**Expected Behavior:**
1. Queue house robbery
2. Get house job
3. Accept job in warehouse
4. Get house location
5. Rob house.

**Actual Behavior:**
1. Queue house robbery
2. Get house job
3. Accept job in warehouse
4. Don't get house location
5. Stuck in queue for rest of storm.

**Comment by feedmeee-x** [comment]
This happened to me while driving to the location. I accepted the house outside a warehouse. I got what I needed and started driving, then the ping disappeared. Linkup keeps telling me I am already doing a job, unable to search for jobs, but I have no location and nothing active.
![image](https://github.com/echoroleplay/feedback/assets/134959051/56a03b62-4d61-43c5-b6a2-bb693a06cb4f)

**Comment by iZolox** [comment]
@feedmeee-x Being in a house does not affect the ability to accept a job could you be more specific as to what happened when you attempted to accept the job?
