### ISSUE TITLE
LinkUp Job Searching not Queueing

### ISSUE THREAD

**Issue by VeracitySZN** [echoroleplay/feedback#60]
After queing for a job, specifically house robbery, my que will freeze and it won't let me que for another job if i cancel. I have also tried logging out through commands and logging back in and ive tried to leave the server and load back in and nothing fixes it.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 

1. Open phone and queue for house robbery
2. Open phone periodically to check queue
3. Realize the queue isn't moving
4. Cancel job
5. Try to renter queue
6. LinkUp says "You are already doing a job, unable to search for jobs."

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.

1. Open phone and queue for house robbery
2. Open phone and see my number moving in the que
3. Accept job
4. Get House location
5. Rob House

**Actual Behavior:** Describe what actually happened instead.

1. Open phone and queue for house robbery
2. Open phone periodically to check queue
3. Realize the queue isn't moving
4. Cancel job
5. Try to renter queue
6. LinkUp says "You are already doing a job, unable to search for jobs."

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 

![image](https://github.com/echoroleplay/feedback/assets/135191685/803dc89b-dd15-48e3-b20f-4e85ef5202df)

**Comment by Breakfastpls** [comment]
Are you sure you did not accept the job as you were cancelling? This prompt comes up once you are on cooldown from a specific job

**Comment by VeracitySZN** [comment]
I don't think so. I've never seen a prompt pop up to accept a job before.

**Comment by iZolox** [comment]
Did you happen to rejoin the server at any point whist in the queue?
