### ISSUE TITLE
Paleto money carts not giving loot

### ISSUE THREAD

**Issue by parkerstan93** [echoroleplay/feedback#61]
**Description:** 2 of the 3 people in my paleto heist looted money carts in the vault, but did not get loot

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. open vault
2. loot carts
3. get no money

**Expected Behavior:** expected to get money from each cart.

**Actual Behavior:** recieved no money from 4 of 6 carts.

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 
https://youtu.be/19mA3wmm32w

**Comment by damightylamb** [comment]
-Was discussed in ticket. Closing for there was no issue with the loot
