### ISSUE TITLE
Drug run completed but still failed?

### ISSUE THREAD

**Issue by Sorrowvi** [echoroleplay/feedback#62]
**Description: *Drug run was completed and after I received the money and it was all done I got a notification on my phone 30 minutes after saying I failed?* 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Brought the car to the destination
2. Unpacked the drugs from the trunk 
3. Received the money in cash
4. 20-30 minutes after I receive a notification of the drug run failing

**Expected Behavior:** Recieve a notification of the run being completed 

**Actual Behavior:** Recieved a notification of it failing even though it was completed and i got the money

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1c1cpD_YCP1DH5/d1337StxGvP8?invite=cr-MSxWUHUsMTIzMDk5ODA5LA

**Comment by damightylamb** [comment]
Pushed a fix for restart
