### ISSUE TITLE
Unable to open DMV Menu

### ISSUE THREAD

**Issue by ImRealRemi** [echoroleplay/feedback#65]
**Description:** : Unable to open the DMV Menu, when attempting to open via radial menu it just shows the cursor with a blank screen.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Walk up to DMV NPC
2.  Use radial key (Mine is mouse 4 re-bind) 
3. Select 'View DMV Options' 

**Expected Behavior:** Expected to be able to view the DMV options to acquire a license.

**Actual Behavior:** Opening the menu just shows the cursor with no options or menu visible, pressing ESC quits out of it.

**Screenshot(s)/Video(s):https://clipchamp.com/watch/xFq7fFfXbDq

**Comment by ImRealRemi** [comment]
Forgot to mention, tried multiple re-boots and even checking video settings (Windowed, full screen etc)

**Comment by C4LLZ** [comment]
Is this still happening?
