### ISSUE TITLE
Becoming aggressive after doing houses

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#66]
**Description:** After you complete house robberies you become aggressive you can no longer enter a car or get on a bike if someone is already on/in it as you will throw them out/off

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Rob House
2. Enter car/bike with someone else in/on it

**Expected Behavior:** Get into the passenger seat

**Actual Behavior:** You throw the driver out

**Comment by damightylamb** [comment]
Kinda funny. Investigating

**Comment by damightylamb** [comment]
Pushed a fix for restart
