### ISSUE TITLE
Not being able to Sign up on LinkUp app.

### ISSUE THREAD

**Issue by Alexmonlol** [echoroleplay/feedback#67]
**Description:** Not being able to signup for a job on the LinkUp app.
Logged in, signed up for "house robbery" then after a while decided to logout. 1.5 hrs later when I logged in agian. I was still in queue (spot 1/30). But I couldn't get a job. Left the queue/ group and then tried to signup again.
At this point you can't sign in for any job. Getting the text "You are already doing a job, unable to search for jobs". 

Been stuck like this for 1 hour now. Probably gonna be like this for the entire reset.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Sign in queue for houses.
2. Logout, come back in WAY later.
3. Be still in the queue, not getting a job. And can't join another job.

**Expected Behavior:** Not being in queue after that long, and being able to sign up for another one. 

**Actual Behavior:** Still in queue when logging in, can't join queue again. No matter the time.

**Screenshot(s)/Video(s):** https://i.imgur.com/r1MJIFf.png

**Comment by FlawwsX** [comment]
Is this still an issue, @Alexmonlol?
