### ISSUE TITLE
Stuck in Boosting queue

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#68]
**Description:** Woke up after restart and joined boosting queue, there is alot of cops but the queue isn't popping. Been in queue for around 4 hours

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Join boost queue
2. Nothing

**Expected Behavior:** Get a boost after a decent amount of time

**Actual Behavior:** Queue doesn't pop

**Comment by damightylamb** [comment]
Pushed a fix that will get implemented tomorrow.

**Comment by Ooodee** [comment]
This is still an ongoing issue, me and multiple others have been in queue for over three hours now without any boost popping up. Boosts were popping up before that, so it seems inconsistent.
