### ISSUE TITLE
Vicodin Runs not working

### ISSUE THREAD

**Issue by feedmeee-x** [echoroleplay/feedback#7]
**Description:** Vicodin runs are able to be started, but the buyers do not do anything once "trade" is clicked on via the third eye menu.

**Reproduction Steps:** 
1. Start Vicodin run
2. Go to the buyer NPC and initiate trade
3. Notice no interaction

**Expected Behavior:** Trade to take place and run to continue

**Actual Behavior:** Nothing happened and run did not continue

**Comment by davidxd33** [comment]
I ran the run for a few minutes and the target option is working for me. Seems to be working as intended, please reopen with a video of this happen along with your F8 client log.

**Comment by feedmeee-x** [comment]
Do i PM you the vid so its not mg'ed?

**Comment by FlawwsX** [comment]
> Do i PM you the vid so its not mg'ed?

You can post the video here.

**Comment by feedmeee-x** [comment]
you fixed it, its working :)
