### ISSUE TITLE
Boosting popping before 30m mark

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#74]
**Description:** Queue for a boost right after restart and instantly get a boost, i feel like these should not be popping until the 30m mark after restart 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Join boost queue
2. Get boost instantly
3. Wait X of the 30 minutes you have for boosting to get your boost

**Expected Behavior:** Boosts to not be popping until 30m after restart

**Actual Behavior:** Instantly popping within 1-2m

**Comment by OmarDam** [comment]
This still happens, boost popped up 21 minutes after restart.
