### ISSUE TITLE
Boostings spawning on each other

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#75]
**Description:** Multiple boosts spawn at the same location

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Claim Boost
2. Go to boost location
3. ...

**Expected Behavior:** 1 car to be there

**Actual Behavior:** Multiple boosts in same area

**Screenshot(s)/Video(s):** https://i.imgur.com/jZSrRq2.jpg

**Comment by davidxd33** [comment]
I believe this was resolved last month with extra checks in place to make sure only one location is used at a time, reopen if this is still happening.
