### ISSUE TITLE
Money run issues

### ISSUE THREAD

**Issue by JohnBeans11** [echoroleplay/feedback#76]
**Description:** When doing money wash, if you go to him with no money he still allows you to do a run, As of now he still gives the drugs and 20-40$ certain times. 

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Go to money wash with no money
2. start money run
3. Get the products

**Expected Behavior:** Still able to do the run fully
**Actual Behavior:** I would think you shouldn't be doing the run without the money. 

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by damightylamb** [comment]
This is not a bug.
