### ISSUE TITLE
House Robbery - Washer is unable to be looted

### ISSUE THREAD

**Issue by Breakfastpls** [echoroleplay/feedback#79]
The Washer item that shows as a lootable item and on loot table is not obtainable. Was unable to during testing and checked on live. Unsure which interiors. It would be the lowend or low end apartment.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Find a Washer
2. Try and loot it
3. No prompt appears

**Comment by SurgeGit** [comment]
The washer is indeed obtainable as I have done it

**Comment by Alexmonlol** [comment]
> The washer is indeed obtainable as I have done it

+1
