### ISSUE TITLE
Random items on the ground all over the place

### ISSUE THREAD

**Issue by QuiggUK** [echoroleplay/feedback#8]
## 🐛 Bug Details

**📖 Description:** Random items on the ground all over the place

**🖱️ Reproduction Steps:**
Go anywhere, look on the ground in different places and items can be found on the floor.
Personally I noticed this first in my warehouse, I found items from house robberies that had no place being there and certainly wasn't me, so could be related to the recent updates to those.

**💡 Expected Behavior:** Items only be in places they have been dropped

**😕 Actual Behavior:** Items on the ground appear to be random and points on the ground are "overlapping" so you're able to find things in different / multiple places.

**🏷️ Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem. 
N/A

**Comment by FlawwsX** [comment]
This has been resolved.
