### ISSUE TITLE
Not enough rep in boosts

### ISSUE THREAD

**Issue by EamonMelo** [echoroleplay/feedback#85]
**Description:** Boosting not giving as much as rep as expected

**Reproduction Steps:** 
1. Step one: Queue for a boost
2. Step two: Do the Boost
3. Step three: Get only one rep for it and needing 680 to Rank up to next rank

**Expected Behavior:** Get a balenced amount of rep in order to reach the next Rank

**Actual Behavior:** Get one rep and needing to boost 600+ cars

Not sure if it was a bug so I put it as one

**Comment by SuspiciouslyStickySock** [comment]
I think this is intended until boosting is more known then we will see either the rep required to go down to the rep gained to go up

**Comment by damightylamb** [comment]
680 is max rep. Not next rep. Not a bug
