### ISSUE TITLE
Prison Food locals getting stuck

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [echoroleplay/feedback#86]
**Description:** When you are serving food to locals at BB the ones that come from the left and right regularly get stuck on the tables

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Go to jail
2. Get kitchen work
3. Serve soup, watch them get stuck on tables

**Expected Behavior:** Locals to walk around the tables

**Actual Behavior:** locals just walk into the desk and then get stuck until the DOC go push them

**Comment by ook3D** [comment]
I believe i know what is causing this, i can take a look.

**Comment by ook3D** [comment]
unable to fix, navmesh is very difficult to troubleshoot / debug. probably wont be fixed sadly :/

**Comment by damightylamb** [comment]
Ill adjust the spawn points
