### ISSUE TITLE
Boosting queue stuck

### ISSUE THREAD

**Issue by Ooodee** [echoroleplay/feedback#87]
Description: Queued in for a boost and been in queue for around 4 hours now. It is also happening with others I know, there was a report about this which was marked as resolved but it is still happening.

Reproduction Steps: Clearly describe the steps to reproduce the bug.

1- Join boosting queue 
2- Get no boost for hours of being in the queue

Expected Behavior: Get a boost after a certain period of time and/or cooldown

Actual Behavior: Stay in queue for hours and hours without being able to boost.

**Comment by Rapid-Zack** [comment]
I will say that I am having this same issue. I have been in que for main storm Thursday and Friday, and from 12 CST to main storm today in que with it not giving me a single boost.

**Comment by FlawwsX** [comment]
A fix has been pushed. Please provide feedback now that the server has restarted.

**Comment by Ooodee** [comment]
After testing it out this latest restart and after the fixes have been pushed, I queued in directly after the restart and got a boost at the 30 minute mark (18:30 EST), completed and queued in again after and have been in queue ever since (>3 hours later). It is now 22:00 EST and still in queue, was able to do one boost since 18:00 EST/restart.

**Comment by FlawwsX** [comment]
According to our logs, the jobs are being assigned just fine. Maybe not at a rate you'd hope for, but it's working.

**Comment by Ooodee** [comment]
I believe it is inconsistent. I did a couple of boosts just fine in one restart (1st restart) today with sensible cooldowns/queue times in between and then sat in queue for 6 hours with no single boost in another restart (2nd Restart/ Main Restart).

 I dont think not being able to do one single boost during a whole 8 hour restart is something normal/intended.

**Comment by feedmeee-x** [comment]
Many people are in the queue for 4+ hours, is this truly normal?
