### ISSUE TITLE
Cannot Select/Delete Chair

### ISSUE THREAD

**Issue by thtgrlcyanide** [echoroleplay/feedback#90]
**Description:** I was decorating the warehouse and I went to look for the office chair you could sit in, I couldn't remember it so I was trying random ones.  This one doesn't show up with a * next to it and its now stuck where I do not want it and I cannot remove it.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Place Padded Rolling Armchair
2.  Try to select it 
3. Can't select it and you can walk through it

**Expected Behavior:** Be able to select it to delete/move it, or at least use it

**Actual Behavior:** Chair is now stuck and cannot delete it or move it

**Screenshot(s)/Video(s):** 
![image (1)](https://github.com/echoroleplay/feedback/assets/135463791/4f9cf72e-b428-4992-b89c-232a9f29deb1)

**Comment by karichandesu** [comment]
If you get close with furniture editor, hold alt and click space. It should select it, the white border might not show is all.

**Comment by thtgrlcyanide** [comment]
Thank you!!! That worked :D
