### ISSUE TITLE
Can't Fuel boats with the new fuel system

### ISSUE THREAD

**Issue by Vallenesca** [echoroleplay/feedback#91]
**Description:** Cant Fuel boats with the new fuel system. We tried with both sides of the boat being closest to the gas pump, and tried to not stretch the nozzles too far so we didn't go boom. Managed to fill with a jerry can, but not everyone will have one.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. park boat next to gas pump
2. grab nozzle and look for "fuel vehicle"
3. nothing appears in the third eye

**Expected Behavior:** Be able to fill a boat with Fuel from the gas pumps at the Marina by Empire/Nautilus

**Actual Behavior:** unable to gas up boat

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by Ponnkun** [comment]
You'll most likely need to use Jerry Cans for now.
