### ISSUE TITLE
Hair disappears when you place a hat on/mask that covers your head.

### ISSUE THREAD

**Issue by xS0uth** [echoroleplay/feedback#95]
**Suggestion Description**
I think it would be nice if whenever you put on a hat or mask that covers your head as well, it removes your hair while wearing the said item so it doesn't clip through the item.

**Reason**
Currently, we have a command /hathair which removes your hair so it doesn't clip through hats and masks but then you need to do the command again for your hair to come back if you remove your mask/hat before doing the command you're bold which I think it just looks weird and iffy for the RP eyes. I think this would look so much better if hair was just removed automatically when you put on a hat or mask that covers your head and whenever you remove the hat/mask, your hair comes back.

**Additional context**
As I stated, personally, it gets annoying when you have to keep doing the command for your hair to stop clipping and then for it to come back. It also looks weird in the RP side whenever you take off your hat/mask before re-apply your hair and weird to also explain whenever someone asks you where your hair dipped and then you become the next Bob Riot (love you really).

**Comment by karichandesu** [comment]
There are so many hairstyles that just do not fit under masks. To automatically remove is a hard no for me, just continue using the command /hathair to remove hair when you want it hidden. It should be manually done. You can use a keybind to make the process simpler if necessary.

**Comment by C4LLZ** [comment]
The command /hathair was implemented for this reason, To go trough all of the clothing just for this will take too much time and is not something we are going to do.
